import type { Story, StoryLine, ComprehensionQuestion } from '../types/content';

// One story per unit. Lines use '' for audio_file — AudioButton shows as disabled
// (graceful fallback) until real audio is recorded/generated.

export const allStories: Story[] = [
  { id: 1,  title: 'Habari za Jirani',    unit_id: 1,  level: 1 },
  { id: 2,  title: 'Saa Ngapi?',          unit_id: 2,  level: 1 },
  { id: 3,  title: 'Siku ya Sokoni',      unit_id: 3,  level: 1 },
  { id: 4,  title: 'Kwa Daktari',         unit_id: 4,  level: 1 },
  { id: 5,  title: 'Familia Yangu',       unit_id: 5,  level: 1 },
  { id: 6,  title: 'Leo Ninafurahi',      unit_id: 6,  level: 1 },
  { id: 7,  title: 'Asubuhi Yangu',       unit_id: 7,  level: 1 },
  { id: 8,  title: 'Wikendi Hii',         unit_id: 8,  level: 1 },
  { id: 9,  title: 'Nilikuwa na Nitakuwa',unit_id: 9,  level: 1 },
  { id: 10, title: 'Mavazi ya Harusi',    unit_id: 10, level: 1 },
  { id: 11, title: 'Nyumba Mpya',         unit_id: 11, level: 1 },
  { id: 12, title: 'Kupika Ugali',        unit_id: 12, level: 1 },
  { id: 13, title: 'Kuvaa Vizuri',        unit_id: 13, level: 1 },
  { id: 14, title: 'Kupotea Mjini',       unit_id: 14, level: 1 },
  { id: 15, title: 'Safari ya Basi',      unit_id: 15, level: 1 },
  { id: 16, title: 'Kununua Nguo',        unit_id: 16, level: 1 },
  { id: 17, title: 'Homa',               unit_id: 17, level: 1 },
  { id: 18, title: 'Siku ya Kwanza',      unit_id: 18, level: 1 },
  { id: 19, title: 'Mvua na Jua',         unit_id: 19, level: 1 },
  { id: 20, title: 'Mazungumzo Mazuri',   unit_id: 20, level: 1 },

  // ── Grammar Track (21-30) ─────────────────────────────────────────────
  { id: 21, title: 'Mimi na Wewe',              unit_id: 21, level: 1 },
  { id: 22, title: 'Shuleni Leo',               unit_id: 22, level: 1 },
  { id: 23, title: 'Sitaki na Sipendi',         unit_id: 23, level: 1 },
  { id: 24, title: 'Nilichofanya Jana',         unit_id: 24, level: 1 },
  { id: 25, title: 'Mipango ya Kesho',          unit_id: 25, level: 1 },
  { id: 26, title: 'Ratiba ya Wiki',            unit_id: 26, level: 1 },
  { id: 27, title: 'Safari ya Hifadhi',         unit_id: 27, level: 1 },
  { id: 28, title: 'Kila Mtu na Kazi Yake',     unit_id: 28, level: 1 },
  { id: 29, title: 'Hesabu Kubwa',              unit_id: 29, level: 1 },
  { id: 30, title: 'Nakupenda na Nakusaidia',   unit_id: 30, level: 1 },

  // ── Expanded Topics (31-40) ───────────────────────────────────────────
  { id: 31, title: 'Mechi ya Mpira',            unit_id: 31, level: 1 },
  { id: 32, title: 'Mtandaoni Leo',             unit_id: 32, level: 1 },
  { id: 33, title: 'Safari ya Zanzibar',        unit_id: 33, level: 1 },
  { id: 34, title: 'Shindano la Mbio',          unit_id: 34, level: 1 },
  { id: 35, title: 'Sokoni Kununua',            unit_id: 35, level: 1 },
  { id: 36, title: 'Siku Yangu Yote',           unit_id: 36, level: 1 },
  { id: 37, title: 'Safari ya Afrika Mashariki', unit_id: 37, level: 1 },
  { id: 38, title: 'Mbele ya Mheshimiwa',       unit_id: 38, level: 1 },
  { id: 39, title: 'Habari za Leo',             unit_id: 39, level: 1 },
  { id: 40, title: 'Siku ya Uchaguzi',          unit_id: 40, level: 1 },
];

// Line IDs: storyId * 100 + lineIndex + 1  (e.g. story 1 = 101–108)
export const allStoryLines: StoryLine[] = [
  // ── Unit 1: Greetings ──────────────────────────────────────────────────
  { id: 101, story_id: 1, line_index: 0, audio_file: '',
    swahili: 'Habari za asubuhi?',
    english: 'Good morning!' },
  { id: 102, story_id: 1, line_index: 1, audio_file: '',
    swahili: 'Nzuri sana, asante! Na wewe?',
    english: 'Very good, thank you! And you?' },
  { id: 103, story_id: 1, line_index: 2, audio_file: '',
    swahili: 'Mimi pia nzuri. Jina lako ni nani?',
    english: 'I am also well. What is your name?' },
  { id: 104, story_id: 1, line_index: 3, audio_file: '',
    swahili: 'Jina langu ni Amina. Na lako?',
    english: 'My name is Amina. And yours?' },
  { id: 105, story_id: 1, line_index: 4, audio_file: '',
    swahili: 'Jina langu ni Baraka. Karibu mtaani mwetu.',
    english: 'My name is Baraka. Welcome to our neighborhood.' },
  { id: 106, story_id: 1, line_index: 5, audio_file: '',
    swahili: 'Asante! Rafiki zangu wanaishi hapa pia.',
    english: 'Thank you! My friends live here too.' },
  { id: 107, story_id: 1, line_index: 6, audio_file: '',
    swahili: 'Samahani, ninaenda shuleni sasa.',
    english: 'Sorry, I am going to school now.' },
  { id: 108, story_id: 1, line_index: 7, audio_file: '',
    swahili: 'Ndio, nami ninaenda. Kwaheri!',
    english: 'Yes, I am going too. Goodbye!' },

  // ── Unit 2: Numbers & Time ────────────────────────────────────────────
  { id: 201, story_id: 2, line_index: 0, audio_file: '',
    swahili: 'Saa ngapi sasa?',
    english: 'What time is it now?' },
  { id: 202, story_id: 2, line_index: 1, audio_file: '',
    swahili: 'Ni saa tisa asubuhi.',
    english: 'It is nine o\'clock in the morning.' },
  { id: 203, story_id: 2, line_index: 2, audio_file: '',
    swahili: 'Kesho ninaenda dukani. Utakuja?',
    english: 'Tomorrow I am going to the shop. Will you come?' },
  { id: 204, story_id: 2, line_index: 3, audio_file: '',
    swahili: 'Ndiyo, tutaenda saa kumi.',
    english: 'Yes, we will go at ten o\'clock.' },
  { id: 205, story_id: 2, line_index: 4, audio_file: '',
    swahili: 'Leo ni siku ya tano ya wiki.',
    english: 'Today is the fifth day of the week.' },
  { id: 206, story_id: 2, line_index: 5, audio_file: '',
    swahili: 'Mwezi huu una siku thelathini.',
    english: 'This month has thirty days.' },
  { id: 207, story_id: 2, line_index: 6, audio_file: '',
    swahili: 'Mwaka huu nimesoma vitabu saba!',
    english: 'This year I have read seven books!' },
  { id: 208, story_id: 2, line_index: 7, audio_file: '',
    swahili: 'Hongera! Wewe ni mtu wa bidii.',
    english: 'Congratulations! You are a hardworking person.' },

  // ── Unit 3: Daily Life ────────────────────────────────────────────────
  { id: 301, story_id: 3, line_index: 0, audio_file: '',
    swahili: 'Asubuhi hii tunaenda sokoni.',
    english: 'This morning we are going to the market.' },
  { id: 302, story_id: 3, line_index: 1, audio_file: '',
    swahili: 'Tutanunua nyama, samaki, na matunda.',
    english: 'We will buy meat, fish, and fruits.' },
  { id: 303, story_id: 3, line_index: 2, audio_file: '',
    swahili: 'Nitapanda basi au gari?',
    english: 'Should I take the bus or car?' },
  { id: 304, story_id: 3, line_index: 3, audio_file: '',
    swahili: 'Panda basi — barabara ina msongamano.',
    english: 'Take the bus — the road has traffic.' },
  { id: 305, story_id: 3, line_index: 4, audio_file: '',
    swahili: 'Hospitali ipo karibu na duka kubwa.',
    english: 'The hospital is near the big shop.' },
  { id: 306, story_id: 3, line_index: 5, audio_file: '',
    swahili: 'Daktari wangu anafanya kazi ofisini pale.',
    english: 'My doctor works in that office there.' },
  { id: 307, story_id: 3, line_index: 6, audio_file: '',
    swahili: 'Mwalimu wetu anakaa nyumbani leo.',
    english: 'Our teacher is staying home today.' },
  { id: 308, story_id: 3, line_index: 7, audio_file: '',
    swahili: 'Nyumba yake iko karibu na mto.',
    english: 'His house is near the river.' },

  // ── Unit 4: The Body ──────────────────────────────────────────────────
  { id: 401, story_id: 4, line_index: 0, audio_file: '',
    swahili: 'Daktari, kichwa changu kinauma sana.',
    english: 'Doctor, my head hurts a lot.' },
  { id: 402, story_id: 4, line_index: 1, audio_file: '',
    swahili: 'Tumbo lako pia linauma?',
    english: 'Does your stomach hurt too?' },
  { id: 403, story_id: 4, line_index: 2, audio_file: '',
    swahili: 'Ndiyo, na mgongo wangu pia.',
    english: 'Yes, and my back too.' },
  { id: 404, story_id: 4, line_index: 3, audio_file: '',
    swahili: 'Nionyeshe mguu wako wa kulia.',
    english: 'Show me your right leg.' },
  { id: 405, story_id: 4, line_index: 4, audio_file: '',
    swahili: 'Goti langu limeumia — nilianguka jana.',
    english: 'My knee is injured — I fell yesterday.' },
  { id: 406, story_id: 4, line_index: 5, audio_file: '',
    swahili: 'Jicho lako ni jekundu. Una homa?',
    english: 'Your eye is red. Do you have a fever?' },
  { id: 407, story_id: 4, line_index: 6, audio_file: '',
    swahili: 'Ndiyo, mwili wangu wote unauma.',
    english: 'Yes, my whole body hurts.' },
  { id: 408, story_id: 4, line_index: 7, audio_file: '',
    swahili: 'Pumzika siku tano na kunywa maji mengi.',
    english: 'Rest for five days and drink lots of water.' },

  // ── Unit 5: Family ────────────────────────────────────────────────────
  { id: 501, story_id: 5, line_index: 0, audio_file: '',
    swahili: 'Familia yangu ni kubwa sana.',
    english: 'My family is very large.' },
  { id: 502, story_id: 5, line_index: 1, audio_file: '',
    swahili: 'Nina baba, mama, kaka wawili na dada mmoja.',
    english: 'I have a father, mother, two brothers and one sister.' },
  { id: 503, story_id: 5, line_index: 2, audio_file: '',
    swahili: 'Babu yangu ana miaka sabini.',
    english: 'My grandfather is seventy years old.' },
  { id: 504, story_id: 5, line_index: 3, audio_file: '',
    swahili: 'Bibi yangu anapika vizuri sana.',
    english: 'My grandmother cooks very well.' },
  { id: 505, story_id: 5, line_index: 4, audio_file: '',
    swahili: 'Mjomba wangu anaishi Mombasa.',
    english: 'My uncle lives in Mombasa.' },
  { id: 506, story_id: 5, line_index: 5, audio_file: '',
    swahili: 'Shangazi yangu ana watoto watatu.',
    english: 'My aunt has three children.' },
  { id: 507, story_id: 5, line_index: 6, audio_file: '',
    swahili: 'Familia yetu inakutana kila Jumapili.',
    english: 'Our family meets every Sunday.' },
  { id: 508, story_id: 5, line_index: 7, audio_file: '',
    swahili: 'Ninawapenda familia yangu sana.',
    english: 'I love my family very much.' },

  // ── Unit 6: Emotions ──────────────────────────────────────────────────
  { id: 601, story_id: 6, line_index: 0, audio_file: '',
    swahili: 'Leo ninafurahi sana!',
    english: 'Today I am very happy!' },
  { id: 602, story_id: 6, line_index: 1, audio_file: '',
    swahili: 'Kwa nini? Habari njema?',
    english: 'Why? Good news?' },
  { id: 603, story_id: 6, line_index: 2, audio_file: '',
    swahili: 'Ndiyo! Nimepata kazi mpya.',
    english: 'Yes! I got a new job.' },
  { id: 604, story_id: 6, line_index: 3, audio_file: '',
    swahili: 'Hongera! Nilikuwa na wasiwasi kwa ajili yako.',
    english: 'Congratulations! I was worried about you.' },
  { id: 605, story_id: 6, line_index: 4, audio_file: '',
    swahili: 'Asante. Nilikuwa na huzuni wiki iliyopita.',
    english: 'Thank you. I was sad last week.' },
  { id: 606, story_id: 6, line_index: 5, audio_file: '',
    swahili: 'Sasa unapaswa kusherehekea!',
    english: 'Now you should celebrate!' },
  { id: 607, story_id: 6, line_index: 6, audio_file: '',
    swahili: 'Ndiyo, nitasherehekea na rafiki zangu.',
    english: 'Yes, I will celebrate with my friends.' },
  { id: 608, story_id: 6, line_index: 7, audio_file: '',
    swahili: 'Usijali — utafanikiwa bila shaka.',
    english: 'Don\'t worry — you will succeed without doubt.' },

  // ── Unit 7: Action Verbs I ────────────────────────────────────────────
  { id: 701, story_id: 7, line_index: 0, audio_file: '',
    swahili: 'Kila asubuhi ninaamka mapema.',
    english: 'Every morning I wake up early.' },
  { id: 702, story_id: 7, line_index: 1, audio_file: '',
    swahili: 'Ninaosha uso na kupiga mswaki meno.',
    english: 'I wash my face and brush my teeth.' },
  { id: 703, story_id: 7, line_index: 2, audio_file: '',
    swahili: 'Kisha ninakula uji na kunywa chai.',
    english: 'Then I eat porridge and drink tea.' },
  { id: 704, story_id: 7, line_index: 3, audio_file: '',
    swahili: 'Watoto wangu wanacheza nje.',
    english: 'My children play outside.' },
  { id: 705, story_id: 7, line_index: 4, audio_file: '',
    swahili: 'Mke wangu anasoma gazeti.',
    english: 'My wife reads the newspaper.' },
  { id: 706, story_id: 7, line_index: 5, audio_file: '',
    swahili: 'Ninakimbia kwa dakika ishirini.',
    english: 'I run for twenty minutes.' },
  { id: 707, story_id: 7, line_index: 6, audio_file: '',
    swahili: 'Baadaye tunaenda pamoja kazini.',
    english: 'Afterwards we go to work together.' },
  { id: 708, story_id: 7, line_index: 7, audio_file: '',
    swahili: 'Jioni tunarudi na kula pamoja.',
    english: 'In the evening we come back and eat together.' },

  // ── Unit 8: Action Verbs II ───────────────────────────────────────────
  { id: 801, story_id: 8, line_index: 0, audio_file: '',
    swahili: 'Wikendi hii tutafanya nini?',
    english: 'What will we do this weekend?' },
  { id: 802, story_id: 8, line_index: 1, audio_file: '',
    swahili: 'Nataka kwenda pwani kuogelea.',
    english: 'I want to go to the beach to swim.' },
  { id: 803, story_id: 8, line_index: 2, audio_file: '',
    swahili: 'Pia tungependa kupiga picha.',
    english: 'We would also like to take photos.' },
  { id: 804, story_id: 8, line_index: 3, audio_file: '',
    swahili: 'Labda tutapanda mlima Jumamosi.',
    english: 'Maybe we will climb the mountain on Saturday.' },
  { id: 805, story_id: 8, line_index: 4, audio_file: '',
    swahili: 'Na Jumapili tutapika nyumbani.',
    english: 'And on Sunday we will cook at home.' },
  { id: 806, story_id: 8, line_index: 5, audio_file: '',
    swahili: 'Nitaandika barua kwa rafiki yangu.',
    english: 'I will write a letter to my friend.' },
  { id: 807, story_id: 8, line_index: 6, audio_file: '',
    swahili: 'Watoto watasaidia kuosha vyombo.',
    english: 'The children will help wash the dishes.' },
  { id: 808, story_id: 8, line_index: 7, audio_file: '',
    swahili: 'Tutafurahia wikendi nzuri sana!',
    english: 'We will enjoy a very good weekend!' },

  // ── Unit 9: Verb Tenses ───────────────────────────────────────────────
  { id: 901, story_id: 9, line_index: 0, audio_file: '',
    swahili: 'Jana nilikwenda sokoni asubuhi.',
    english: 'Yesterday I went to the market in the morning.' },
  { id: 902, story_id: 9, line_index: 1, audio_file: '',
    swahili: 'Nilinunua nyama na mboga nyingi.',
    english: 'I bought meat and many vegetables.' },
  { id: 903, story_id: 9, line_index: 2, audio_file: '',
    swahili: 'Wiki iliyopita nilikuwa mgonjwa.',
    english: 'Last week I was sick.' },
  { id: 904, story_id: 9, line_index: 3, audio_file: '',
    swahili: 'Sikuweza kwenda kazini kwa siku tatu.',
    english: 'I could not go to work for three days.' },
  { id: 905, story_id: 9, line_index: 4, audio_file: '',
    swahili: 'Sasa nimepona na ninafanya kazi.',
    english: 'Now I have recovered and I am working.' },
  { id: 906, story_id: 9, line_index: 5, audio_file: '',
    swahili: 'Kesho nitaenda hospitali kwa ukaguzi.',
    english: 'Tomorrow I will go to the hospital for a check-up.' },
  { id: 907, story_id: 9, line_index: 6, audio_file: '',
    swahili: 'Mwezi ujao nitasafiri kwenda Dar es Salaam.',
    english: 'Next month I will travel to Dar es Salaam.' },
  { id: 908, story_id: 9, line_index: 7, audio_file: '',
    swahili: 'Nitarudi baada ya wiki mbili.',
    english: 'I will return after two weeks.' },

  // ── Unit 10: Colours & Adjectives ────────────────────────────────────
  { id: 1001, story_id: 10, line_index: 0, audio_file: '',
    swahili: 'Nataka kununua gauni kwa harusi.',
    english: 'I want to buy a dress for the wedding.' },
  { id: 1002, story_id: 10, line_index: 1, audio_file: '',
    swahili: 'Gauni jekundu ni zuri sana.',
    english: 'The red dress is very beautiful.' },
  { id: 1003, story_id: 10, line_index: 2, audio_file: '',
    swahili: 'Lakini mimi ninapenda rangi ya bluu.',
    english: 'But I prefer the colour blue.' },
  { id: 1004, story_id: 10, line_index: 3, audio_file: '',
    swahili: 'Bluu nyeupe au bluu giza?',
    english: 'Light blue or dark blue?' },
  { id: 1005, story_id: 10, line_index: 4, audio_file: '',
    swahili: 'Bluu nyeupe — ni rangi nzuri na safi.',
    english: 'Light blue — it is a nice clean colour.' },
  { id: 1006, story_id: 10, line_index: 5, audio_file: '',
    swahili: 'Duka hili lina gauni kubwa na ndogo.',
    english: 'This shop has big and small dresses.' },
  { id: 1007, story_id: 10, line_index: 6, audio_file: '',
    swahili: 'Gauni hii ni ndefu sana kwa mimi.',
    english: 'This dress is too long for me.' },
  { id: 1008, story_id: 10, line_index: 7, audio_file: '',
    swahili: 'Tutapata gauni fupi ya rangi ya njano.',
    english: 'We will find a short yellow dress.' },

  // ── Unit 11: Home & Furniture ─────────────────────────────────────────
  { id: 1101, story_id: 11, line_index: 0, audio_file: '',
    swahili: 'Nyumba mpya yako ni nzuri sana!',
    english: 'Your new house is very beautiful!' },
  { id: 1102, story_id: 11, line_index: 1, audio_file: '',
    swahili: 'Asante. Ina vyumba vinne.',
    english: 'Thank you. It has four rooms.' },
  { id: 1103, story_id: 11, line_index: 2, audio_file: '',
    swahili: 'Sebule yako ina viti na meza kubwa.',
    english: 'Your living room has chairs and a big table.' },
  { id: 1104, story_id: 11, line_index: 3, audio_file: '',
    swahili: 'Ndiyo, na sofa mpya ya rangi ya kahawia.',
    english: 'Yes, and a new brown sofa.' },
  { id: 1105, story_id: 11, line_index: 4, audio_file: '',
    swahili: 'Jikoni lako lina jokofu na jiko?',
    english: 'Does your kitchen have a fridge and stove?' },
  { id: 1106, story_id: 11, line_index: 5, audio_file: '',
    swahili: 'Ndiyo, na kabati kubwa la vyombo.',
    english: 'Yes, and a big dish cupboard.' },
  { id: 1107, story_id: 11, line_index: 6, audio_file: '',
    swahili: 'Chumba cha kulalia ni kikubwa?',
    english: 'Is the bedroom large?' },
  { id: 1108, story_id: 11, line_index: 7, audio_file: '',
    swahili: 'Ndiyo, kina kitanda kikubwa na mto laini.',
    english: 'Yes, it has a big bed and a soft pillow.' },

  // ── Unit 12: Food & Cooking ───────────────────────────────────────────
  { id: 1201, story_id: 12, line_index: 0, audio_file: '',
    swahili: 'Nakupikia nini leo jioni?',
    english: 'What shall I cook for you tonight?' },
  { id: 1202, story_id: 12, line_index: 1, audio_file: '',
    swahili: 'Pika ugali na sukuma wiki tafadhali.',
    english: 'Cook ugali and collard greens please.' },
  { id: 1203, story_id: 12, line_index: 2, audio_file: '',
    swahili: 'Sawa. Nitaongeza samaki wa kukaanga pia.',
    english: 'Okay. I will also add some fried fish.' },
  { id: 1204, story_id: 12, line_index: 3, audio_file: '',
    swahili: 'Vizuri sana! Ninapenda chakula hicho.',
    english: 'Very good! I love that food.' },
  { id: 1205, story_id: 12, line_index: 4, audio_file: '',
    swahili: 'Je, una vitunguu na nyanya?',
    english: 'Do you have onions and tomatoes?' },
  { id: 1206, story_id: 12, line_index: 5, audio_file: '',
    swahili: 'Ndiyo, na mafuta ya kupikia.',
    english: 'Yes, and cooking oil.' },
  { id: 1207, story_id: 12, line_index: 6, audio_file: '',
    swahili: 'Chakula kitakuwa tayari saa moja.',
    english: 'Food will be ready in one hour.' },
  { id: 1208, story_id: 12, line_index: 7, audio_file: '',
    swahili: 'Asante sana! Chakula chako ni kitamu daima.',
    english: 'Thank you so much! Your food is always delicious.' },

  // ── Unit 13: Clothing ─────────────────────────────────────────────────
  { id: 1301, story_id: 13, line_index: 0, audio_file: '',
    swahili: 'Kesho ni harusi ya ndugu yangu.',
    english: 'Tomorrow is my sibling\'s wedding.' },
  { id: 1302, story_id: 13, line_index: 1, audio_file: '',
    swahili: 'Utavaa nini?',
    english: 'What will you wear?' },
  { id: 1303, story_id: 13, line_index: 2, audio_file: '',
    swahili: 'Nataka kuvaa suruali ya bluu na shati nyeupe.',
    english: 'I want to wear blue trousers and a white shirt.' },
  { id: 1304, story_id: 13, line_index: 3, audio_file: '',
    swahili: 'Na viatu gani?',
    english: 'And which shoes?' },
  { id: 1305, story_id: 13, line_index: 4, audio_file: '',
    swahili: 'Viatu vya ngozi vya rangi ya kahawia.',
    english: 'Brown leather shoes.' },
  { id: 1306, story_id: 13, line_index: 5, audio_file: '',
    swahili: 'Vizuri sana! Na mke wako atavaa nini?',
    english: 'Very nice! And what will your wife wear?' },
  { id: 1307, story_id: 13, line_index: 6, audio_file: '',
    swahili: 'Atavaa gauni jekundu zuri.',
    english: 'She will wear a beautiful red dress.' },
  { id: 1308, story_id: 13, line_index: 7, audio_file: '',
    swahili: 'Mtaonekana vizuri sana pamoja!',
    english: 'You will both look very good together!' },

  // ── Unit 14: Directions ───────────────────────────────────────────────
  { id: 1401, story_id: 14, line_index: 0, audio_file: '',
    swahili: 'Samahani, hospitali iko wapi?',
    english: 'Excuse me, where is the hospital?' },
  { id: 1402, story_id: 14, line_index: 1, audio_file: '',
    swahili: 'Nenda moja kwa moja hadi mwisho wa barabara.',
    english: 'Go straight to the end of the road.' },
  { id: 1403, story_id: 14, line_index: 2, audio_file: '',
    swahili: 'Kisha geuka kulia.',
    english: 'Then turn right.' },
  { id: 1404, story_id: 14, line_index: 3, audio_file: '',
    swahili: 'Nitapita karibu na duka kubwa?',
    english: 'Will I pass near a big shop?' },
  { id: 1405, story_id: 14, line_index: 4, audio_file: '',
    swahili: 'Ndiyo, duka liko upande wa kushoto.',
    english: 'Yes, the shop is on the left side.' },
  { id: 1406, story_id: 14, line_index: 5, audio_file: '',
    swahili: 'Hospitali iko mbali au karibu?',
    english: 'Is the hospital far or near?' },
  { id: 1407, story_id: 14, line_index: 6, audio_file: '',
    swahili: 'Iko karibu sana — dakika tano kwa miguu.',
    english: 'It is very near — five minutes on foot.' },
  { id: 1408, story_id: 14, line_index: 7, audio_file: '',
    swahili: 'Asante sana kwa msaada wako!',
    english: 'Thank you very much for your help!' },

  // ── Unit 15: Transport ────────────────────────────────────────────────
  { id: 1501, story_id: 15, line_index: 0, audio_file: '',
    swahili: 'Ninataka kwenda Nairobi — basi au treni?',
    english: 'I want to go to Nairobi — bus or train?' },
  { id: 1502, story_id: 15, line_index: 1, audio_file: '',
    swahili: 'Basi ni ya bei nafuu zaidi.',
    english: 'The bus is cheaper.' },
  { id: 1503, story_id: 15, line_index: 2, audio_file: '',
    swahili: 'Treni ni ya haraka zaidi na vizuri zaidi.',
    english: 'The train is faster and more comfortable.' },
  { id: 1504, story_id: 15, line_index: 3, audio_file: '',
    swahili: 'Basi inaondoka saa ngapi?',
    english: 'What time does the bus leave?' },
  { id: 1505, story_id: 15, line_index: 4, audio_file: '',
    swahili: 'Inaondoka saa nne asubuhi.',
    english: 'It leaves at four in the morning.' },
  { id: 1506, story_id: 15, line_index: 5, audio_file: '',
    swahili: 'Na treni inaondoka saa ngapi?',
    english: 'And what time does the train leave?' },
  { id: 1507, story_id: 15, line_index: 6, audio_file: '',
    swahili: 'Treni inaondoka saa saba asubuhi.',
    english: 'The train leaves at seven in the morning.' },
  { id: 1508, story_id: 15, line_index: 7, audio_file: '',
    swahili: 'Nitapanda treni — sinachukia kuamka mapema.',
    english: 'I will take the train — I don\'t mind waking up early.' },

  // ── Unit 16: Shopping & Money ─────────────────────────────────────────
  { id: 1601, story_id: 16, line_index: 0, audio_file: '',
    swahili: 'Bei ya nguo hii ni ngapi?',
    english: 'How much does this piece of clothing cost?' },
  { id: 1602, story_id: 16, line_index: 1, audio_file: '',
    swahili: 'Ni shilingi elfu tano.',
    english: 'It is five thousand shillings.' },
  { id: 1603, story_id: 16, line_index: 2, audio_file: '',
    swahili: 'Ni ghali sana! Niuzie kwa elfu tatu.',
    english: 'It is too expensive! Sell it to me for three thousand.' },
  { id: 1604, story_id: 16, line_index: 3, audio_file: '',
    swahili: 'Haiwezekani — gharama yangu ni elfu nne.',
    english: 'Impossible — my cost is four thousand.' },
  { id: 1605, story_id: 16, line_index: 4, audio_file: '',
    swahili: 'Sawa, nitalipia elfu tatu na mia tano.',
    english: 'Okay, I will pay three thousand five hundred.' },
  { id: 1606, story_id: 16, line_index: 5, audio_file: '',
    swahili: 'Sawa kabisa. Hapa ni nguo yako.',
    english: 'Agreed. Here is your clothing.' },
  { id: 1607, story_id: 16, line_index: 6, audio_file: '',
    swahili: 'Je, unakubali pesa ya simu?',
    english: 'Do you accept mobile money?' },
  { id: 1608, story_id: 16, line_index: 7, audio_file: '',
    swahili: 'Ndiyo, tunapokea M-Pesa.',
    english: 'Yes, we accept M-Pesa.' },

  // ── Unit 17: Health ───────────────────────────────────────────────────
  { id: 1701, story_id: 17, line_index: 0, audio_file: '',
    swahili: 'Ninajisikia vibaya sana leo.',
    english: 'I feel very unwell today.' },
  { id: 1702, story_id: 17, line_index: 1, audio_file: '',
    swahili: 'Una dalili gani?',
    english: 'What are your symptoms?' },
  { id: 1703, story_id: 17, line_index: 2, audio_file: '',
    swahili: 'Nina homa na kichwa kinauma.',
    english: 'I have a fever and my head hurts.' },
  { id: 1704, story_id: 17, line_index: 3, audio_file: '',
    swahili: 'Nimekuwa mgonjwa kwa siku mbili.',
    english: 'I have been sick for two days.' },
  { id: 1705, story_id: 17, line_index: 4, audio_file: '',
    swahili: 'Unahitaji kwenda kliniki haraka.',
    english: 'You need to go to the clinic quickly.' },
  { id: 1706, story_id: 17, line_index: 5, audio_file: '',
    swahili: 'Daktari atakupa dawa sahihi.',
    english: 'The doctor will give you the right medicine.' },
  { id: 1707, story_id: 17, line_index: 6, audio_file: '',
    swahili: 'Kaa nyumbani, usisafiri.',
    english: 'Stay home, do not travel.' },
  { id: 1708, story_id: 17, line_index: 7, audio_file: '',
    swahili: 'Asante. Nitapona haraka na dawa nzuri.',
    english: 'Thank you. I will recover quickly with good medicine.' },

  // ── Unit 18: School & Work ────────────────────────────────────────────
  { id: 1801, story_id: 18, line_index: 0, audio_file: '',
    swahili: 'Leo ni siku yangu ya kwanza kazini.',
    english: 'Today is my first day at work.' },
  { id: 1802, story_id: 18, line_index: 1, audio_file: '',
    swahili: 'Ofisi iko ghorofa ya tatu.',
    english: 'The office is on the third floor.' },
  { id: 1803, story_id: 18, line_index: 2, audio_file: '',
    swahili: 'Wafanyakazi wenzangu ni wazuri sana.',
    english: 'My coworkers are very kind.' },
  { id: 1804, story_id: 18, line_index: 3, audio_file: '',
    swahili: 'Nitaandika ripoti ya kwanza wiki hii.',
    english: 'I will write my first report this week.' },
  { id: 1805, story_id: 18, line_index: 4, audio_file: '',
    swahili: 'Mshahara wangu utaingia mwezi ujao.',
    english: 'My salary will come next month.' },
  { id: 1806, story_id: 18, line_index: 5, audio_file: '',
    swahili: 'Ninahitaji kompyuta na kalamu.',
    english: 'I need a computer and a pen.' },
  { id: 1807, story_id: 18, line_index: 6, audio_file: '',
    swahili: 'Mwalimu wangu alisema kufanya kazi kwa bidii.',
    english: 'My teacher told me to work hard.' },
  { id: 1808, story_id: 18, line_index: 7, audio_file: '',
    swahili: 'Niko tayari kufanya kazi nzuri!',
    english: 'I am ready to do good work!' },

  // ── Unit 19: Nature & Weather ─────────────────────────────────────────
  { id: 1901, story_id: 19, line_index: 0, audio_file: '',
    swahili: 'Leo hali ya hewa ni nzuri sana.',
    english: 'Today the weather is very beautiful.' },
  { id: 1902, story_id: 19, line_index: 1, audio_file: '',
    swahili: 'Ndiyo, jua linawaka sana.',
    english: 'Yes, the sun is shining brightly.' },
  { id: 1903, story_id: 19, line_index: 2, audio_file: '',
    swahili: 'Kesho itakuwa na mvua?',
    english: 'Will it rain tomorrow?' },
  { id: 1904, story_id: 19, line_index: 3, audio_file: '',
    swahili: 'Redio ilisema itanyesha mchana.',
    english: 'The radio said it will rain in the afternoon.' },
  { id: 1905, story_id: 19, line_index: 4, audio_file: '',
    swahili: 'Basi tutaenda pwani asubuhi.',
    english: 'Then we will go to the beach in the morning.' },
  { id: 1906, story_id: 19, line_index: 5, audio_file: '',
    swahili: 'Pwani ina bahari nzuri na mchanga mzuri.',
    english: 'The beach has beautiful sea and nice sand.' },
  { id: 1907, story_id: 19, line_index: 6, audio_file: '',
    swahili: 'Ninapenda kuona ndege wakiimba msituni.',
    english: 'I love to see birds singing in the forest.' },
  { id: 1908, story_id: 19, line_index: 7, audio_file: '',
    swahili: 'Maisha ni mazuri wakati hali ya hewa ni nzuri!',
    english: 'Life is good when the weather is nice!' },

  // ── Unit 20: Phrases ──────────────────────────────────────────────────
  { id: 2001, story_id: 20, line_index: 0, audio_file: '',
    swahili: 'Habari za kazi?',
    english: 'How is work going?' },
  { id: 2002, story_id: 20, line_index: 1, audio_file: '',
    swahili: 'Nzuri, asante. Ninafanya kazi nzuri.',
    english: 'Good, thank you. I am doing good work.' },
  { id: 2003, story_id: 20, line_index: 2, audio_file: '',
    swahili: 'Karibu tena ofisini mwetu.',
    english: 'Welcome back to our office.' },
  { id: 2004, story_id: 20, line_index: 3, audio_file: '',
    swahili: 'Asante sana. Ninafurahi kuwa hapa.',
    english: 'Thank you very much. I am happy to be here.' },
  { id: 2005, story_id: 20, line_index: 4, audio_file: '',
    swahili: 'Samahani, ningehitaji msaada wako kidogo.',
    english: 'Excuse me, I would need your help a little.' },
  { id: 2006, story_id: 20, line_index: 5, audio_file: '',
    swahili: 'Hakuna shida! Nikuonyeshe nini?',
    english: 'No problem! What should I show you?' },
  { id: 2007, story_id: 20, line_index: 6, audio_file: '',
    swahili: 'Tafadhali nieleze jinsi ya kutumia mfumo huu.',
    english: 'Please explain how to use this system.' },
  { id: 2008, story_id: 20, line_index: 7, audio_file: '',
    swahili: 'Bila shaka! Kaa karibu — nitakufundisha.',
    english: 'Of course! Come close — I will teach you.' },

  // ── Unit 21: Pronouns & "To Be" ──────────────────────────────────────
  { id: 2101, story_id: 21, line_index: 0, audio_file: '',
    swahili: 'Mimi ni Juma. Wewe ni nani?',
    english: 'I am Juma. Who are you?' },
  { id: 2102, story_id: 21, line_index: 1, audio_file: '',
    swahili: 'Mimi ni Asha. Hii ni familia yangu.',
    english: 'I am Asha. This is my family.' },
  { id: 2103, story_id: 21, line_index: 2, audio_file: '',
    swahili: 'Yeye ni nani?',
    english: 'Who is he/she?' },
  { id: 2104, story_id: 21, line_index: 3, audio_file: '',
    swahili: 'Yeye ni kaka yangu. Jina lake ni Baraka.',
    english: 'He is my brother. His name is Baraka.' },
  { id: 2105, story_id: 21, line_index: 4, audio_file: '',
    swahili: 'Sisi ni wanafunzi wa Kiswahili.',
    english: 'We are Swahili students.' },
  { id: 2106, story_id: 21, line_index: 5, audio_file: '',
    swahili: 'Nyinyi ni marafiki wazuri.',
    english: 'You all are good friends.' },
  { id: 2107, story_id: 21, line_index: 6, audio_file: '',
    swahili: 'Hii ni shule yetu. Si kubwa lakini ni nzuri.',
    english: 'This is our school. It is not big but it is nice.' },
  { id: 2108, story_id: 21, line_index: 7, audio_file: '',
    swahili: 'Wao pia ni wanafunzi. Tunapenda kusoma pamoja.',
    english: 'They are also students. We like to study together.' },

  // ── Unit 22: Present Tense -NA- ──────────────────────────────────────
  { id: 2201, story_id: 22, line_index: 0, audio_file: '',
    swahili: 'Ninasoma kitabu cha Kiswahili.',
    english: 'I am reading a Swahili book.' },
  { id: 2202, story_id: 22, line_index: 1, audio_file: '',
    swahili: 'Unasoma kitabu gani?',
    english: 'What book are you reading?' },
  { id: 2203, story_id: 22, line_index: 2, audio_file: '',
    swahili: 'Ninasoma kitabu cha hadithi. Ninapenda kusoma.',
    english: 'I am reading a story book. I like to read.' },
  { id: 2204, story_id: 22, line_index: 3, audio_file: '',
    swahili: 'Anasoma pia? Huyo ni nani?',
    english: 'Is he also reading? Who is that?' },
  { id: 2205, story_id: 22, line_index: 4, audio_file: '',
    swahili: 'Anasoma darasani. Anapenda sana kujifunza.',
    english: 'He is reading in class. He loves to learn.' },
  { id: 2206, story_id: 22, line_index: 5, audio_file: '',
    swahili: 'Tunasoma pamoja kila asubuhi.',
    english: 'We read together every morning.' },
  { id: 2207, story_id: 22, line_index: 6, audio_file: '',
    swahili: 'Mnasoma vizuri. Hongera!',
    english: 'You all read well. Congratulations!' },
  { id: 2208, story_id: 22, line_index: 7, audio_file: '',
    swahili: 'Wanasoma vitabu vingi. Wanajua Kiswahili vizuri.',
    english: 'They read many books. They know Swahili well.' },

  // ── Unit 23: Negation ────────────────────────────────────────────────
  { id: 2301, story_id: 23, line_index: 0, audio_file: '',
    swahili: 'Unapenda chai?',
    english: 'Do you like tea?' },
  { id: 2302, story_id: 23, line_index: 1, audio_file: '',
    swahili: 'Sipendi chai. Napenda kahawa.',
    english: 'I do not like tea. I like coffee.' },
  { id: 2303, story_id: 23, line_index: 2, audio_file: '',
    swahili: 'Hapendi pilipili? Kwa nini?',
    english: 'He does not like pepper? Why?' },
  { id: 2304, story_id: 23, line_index: 3, audio_file: '',
    swahili: 'Hapendi pilipili kwa sababu ni kali sana.',
    english: 'He does not like pepper because it is very hot.' },
  { id: 2305, story_id: 23, line_index: 4, audio_file: '',
    swahili: 'Sikuli nyama. Mimi ni mla mboga.',
    english: 'I do not eat meat. I am a vegetarian.' },
  { id: 2306, story_id: 23, line_index: 5, audio_file: '',
    swahili: 'Sielewi. Unaweza kusema tena?',
    english: 'I do not understand. Can you say it again?' },
  { id: 2307, story_id: 23, line_index: 6, audio_file: '',
    swahili: 'Hatusomi Jumapili. Tunapumzika.',
    english: 'We do not study on Sunday. We rest.' },
  { id: 2308, story_id: 23, line_index: 7, audio_file: '',
    swahili: 'Sitaki kwenda leo. Siwezi kutembea mbali.',
    english: 'I do not want to go today. I cannot walk far.' },

  // ── Unit 24: Past Tense -LI- ─────────────────────────────────────────
  { id: 2401, story_id: 24, line_index: 0, audio_file: '',
    swahili: 'Ulikuwa wapi jana?',
    english: 'Where were you yesterday?' },
  { id: 2402, story_id: 24, line_index: 1, audio_file: '',
    swahili: 'Nilikwenda sokoni asubuhi.',
    english: 'I went to the market in the morning.' },
  { id: 2403, story_id: 24, line_index: 2, audio_file: '',
    swahili: 'Ulinunua nini?',
    english: 'What did you buy?' },
  { id: 2404, story_id: 24, line_index: 3, audio_file: '',
    swahili: 'Nilinunua matunda na mboga.',
    english: 'I bought fruits and vegetables.' },
  { id: 2405, story_id: 24, line_index: 4, audio_file: '',
    swahili: 'Alikuja jana jioni. Aliongea nami kwa muda mrefu.',
    english: 'He came yesterday evening. He spoke with me for a long time.' },
  { id: 2406, story_id: 24, line_index: 5, audio_file: '',
    swahili: 'Tulikula pamoja. Chakula kilikuwa kitamu.',
    english: 'We ate together. The food was delicious.' },
  { id: 2407, story_id: 24, line_index: 6, audio_file: '',
    swahili: 'Walikuwa wagonjwa wiki iliyopita.',
    english: 'They were sick last week.' },
  { id: 2408, story_id: 24, line_index: 7, audio_file: '',
    swahili: 'Nilifanya kazi nyingi lakini nimefurahi.',
    english: 'I did a lot of work but I am happy.' },

  // ── Unit 25: Future Tense -TA- ───────────────────────────────────────
  { id: 2501, story_id: 25, line_index: 0, audio_file: '',
    swahili: 'Nitafanya nini kesho?',
    english: 'What will I do tomorrow?' },
  { id: 2502, story_id: 25, line_index: 1, audio_file: '',
    swahili: 'Nitasoma kitabu hiki asubuhi.',
    english: 'I will read this book in the morning.' },
  { id: 2503, story_id: 25, line_index: 2, audio_file: '',
    swahili: 'Utakwenda wapi mchana?',
    english: 'Where will you go in the afternoon?' },
  { id: 2504, story_id: 25, line_index: 3, audio_file: '',
    swahili: 'Nitakwenda hospitali. Daktari atanisaidia.',
    english: 'I will go to the hospital. The doctor will help me.' },
  { id: 2505, story_id: 25, line_index: 4, audio_file: '',
    swahili: 'Tutakwenda pwani pamoja Jumapili.',
    english: 'We will go to the beach together on Sunday.' },
  { id: 2506, story_id: 25, line_index: 5, audio_file: '',
    swahili: 'Nitanunua nguo mpya kabla ya safari.',
    english: 'I will buy new clothes before the trip.' },
  { id: 2507, story_id: 25, line_index: 6, audio_file: '',
    swahili: 'Nitasema ukweli. Nitarudi mapema.',
    english: 'I will speak the truth. I will return early.' },
  { id: 2508, story_id: 25, line_index: 7, audio_file: '',
    swahili: 'Tutaona hali ya hewa. Ikiwa nzuri, tutakwenda.',
    english: 'We will see the weather. If it is good, we will go.' },

  // ── Unit 26: Days & Time Phrases ─────────────────────────────────────
  { id: 2601, story_id: 26, line_index: 0, audio_file: '',
    swahili: 'Leo ni Jumatatu. Wiki mpya imeanza.',
    english: 'Today is Monday. A new week has begun.' },
  { id: 2602, story_id: 26, line_index: 1, audio_file: '',
    swahili: 'Jumanne tuna mkutano muhimu ofisini.',
    english: 'On Tuesday we have an important meeting at the office.' },
  { id: 2603, story_id: 26, line_index: 2, audio_file: '',
    swahili: 'Jumatano ni katikati ya wiki. Najisikia vizuri.',
    english: 'Wednesday is the middle of the week. I feel good.' },
  { id: 2604, story_id: 26, line_index: 3, audio_file: '',
    swahili: 'Alhamisi ninakwenda kwa daktari.',
    english: 'On Thursday I go to the doctor.' },
  { id: 2605, story_id: 26, line_index: 4, audio_file: '',
    swahili: 'Ijumaa ni siku ya mwisho ya kazi.',
    english: 'Friday is the last day of work.' },
  { id: 2606, story_id: 26, line_index: 5, audio_file: '',
    swahili: 'Jumamosi tunapumzika na kucheza.',
    english: 'On Saturday we rest and play.' },
  { id: 2607, story_id: 26, line_index: 6, audio_file: '',
    swahili: 'Jumapili ninaenda kanisani asubuhi.',
    english: 'On Sunday I go to church in the morning.' },
  { id: 2608, story_id: 26, line_index: 7, audio_file: '',
    swahili: 'Wiki ijayo nitasafiri Mombasa. Nitaondoka mapema.',
    english: 'Next week I will travel to Mombasa. I will leave early.' },

  // ── Unit 27: Animals ─────────────────────────────────────────────────
  { id: 2701, story_id: 27, line_index: 0, audio_file: '',
    swahili: 'Tunaenda hifadhi ya wanyama leo!',
    english: 'We are going to the national park today!' },
  { id: 2702, story_id: 27, line_index: 1, audio_file: '',
    swahili: 'Angalia! Simba amelala chini ya mti.',
    english: 'Look! A lion is sleeping under the tree.' },
  { id: 2703, story_id: 27, line_index: 2, audio_file: '',
    swahili: 'Tembo ni mkubwa sana. Ana masikio makubwa.',
    english: 'The elephant is very big. It has large ears.' },
  { id: 2704, story_id: 27, line_index: 3, audio_file: '',
    swahili: 'Twiga ana shingo ndefu. Anafikia matawi ya juu.',
    english: 'The giraffe has a long neck. It reaches the high branches.' },
  { id: 2705, story_id: 27, line_index: 4, audio_file: '',
    swahili: 'Nyani wanacheza kwenye miti. Wana furaha.',
    english: 'The monkeys are playing in the trees. They are happy.' },
  { id: 2706, story_id: 27, line_index: 5, audio_file: '',
    swahili: 'Kiboko yuko majini. Anatoka tu kupumua.',
    english: 'The hippo is in the water. It is just coming out to breathe.' },
  { id: 2707, story_id: 27, line_index: 6, audio_file: '',
    swahili: 'Chui ana rangi nzuri. Lakini ni hatari.',
    english: 'The leopard has beautiful colours. But it is dangerous.' },
  { id: 2708, story_id: 27, line_index: 7, audio_file: '',
    swahili: 'Safari hii ni nzuri! Tumewaona wanyama wengi.',
    english: 'This safari is wonderful! We have seen many animals.' },

  // ── Unit 28: Jobs & Professions ──────────────────────────────────────
  { id: 2801, story_id: 28, line_index: 0, audio_file: '',
    swahili: 'Unataka kuwa nini utakapokuwa mkubwa?',
    english: 'What do you want to be when you grow up?' },
  { id: 2802, story_id: 28, line_index: 1, audio_file: '',
    swahili: 'Nataka kuwa daktari. Napenda kusaidia watu.',
    english: 'I want to be a doctor. I like to help people.' },
  { id: 2803, story_id: 28, line_index: 2, audio_file: '',
    swahili: 'Kaka yangu ni mhandisi. Anajenga madaraja.',
    english: 'My brother is an engineer. He builds bridges.' },
  { id: 2804, story_id: 28, line_index: 3, audio_file: '',
    swahili: 'Mama yangu ni mwalimu. Anafundisha watoto.',
    english: 'My mother is a teacher. She teaches children.' },
  { id: 2805, story_id: 28, line_index: 4, audio_file: '',
    swahili: 'Baba yangu ni mkulima. Analima mahindi na maharage.',
    english: 'My father is a farmer. He grows maize and beans.' },
  { id: 2806, story_id: 28, line_index: 5, audio_file: '',
    swahili: 'Dada yangu ni muuguzi. Anafanya kazi hospitalini.',
    english: 'My sister is a nurse. She works at the hospital.' },
  { id: 2807, story_id: 28, line_index: 6, audio_file: '',
    swahili: 'Mjomba wangu ni rubani. Anasafiri nchi nyingi.',
    english: 'My uncle is a pilot. He travels to many countries.' },
  { id: 2808, story_id: 28, line_index: 7, audio_file: '',
    swahili: 'Kila mtu ana kazi muhimu. Kazi zote zina heshima.',
    english: 'Everyone has an important job. All jobs have dignity.' },

  // ── Unit 29: Numbers 11–1000 ─────────────────────────────────────────
  { id: 2901, story_id: 29, line_index: 0, audio_file: '',
    swahili: 'Hizi ni ngapi?',
    english: 'How many are these?' },
  { id: 2902, story_id: 29, line_index: 1, audio_file: '',
    swahili: 'Hizi ni kumi na tano.',
    english: 'These are fifteen.' },
  { id: 2903, story_id: 29, line_index: 2, audio_file: '',
    swahili: 'Babu ana miaka sabini. Bibi ana miaka sitini.',
    english: 'Grandfather is seventy. Grandmother is sixty.' },
  { id: 2904, story_id: 29, line_index: 3, audio_file: '',
    swahili: 'Ninahitaji shilingi mia tano.',
    english: 'I need five hundred shillings.' },
  { id: 2905, story_id: 29, line_index: 4, audio_file: '',
    swahili: 'Kodi ya nyumba ni elfu hamsini kwa mwezi.',
    english: 'The house rent is fifty thousand per month.' },
  { id: 2906, story_id: 29, line_index: 5, audio_file: '',
    swahili: 'Nipe nusu ya mkate, tafadhali.',
    english: 'Give me half of the bread, please.' },
  { id: 2907, story_id: 29, line_index: 6, audio_file: '',
    swahili: 'Robo ya wanafunzi walifaulu mtihani.',
    english: 'A quarter of the students passed the exam.' },
  { id: 2908, story_id: 29, line_index: 7, audio_file: '',
    swahili: 'Jumla ni mia mbili na thelathini. Hiyo ni bei nzuri!',
    english: 'The total is two hundred and thirty. That is a good price!' },

  // ── Unit 30: Object Infixes ──────────────────────────────────────────
  { id: 3001, story_id: 30, line_index: 0, audio_file: '',
    swahili: 'Ninakupenda mama.',
    english: 'I love you, mum.' },
  { id: 3002, story_id: 30, line_index: 1, audio_file: '',
    swahili: 'Nakupenda pia mwanangu.',
    english: 'I love you too, my child.' },
  { id: 3003, story_id: 30, line_index: 2, audio_file: '',
    swahili: 'Ananipenda kwa moyo wake wote.',
    english: 'He loves me with all his heart.' },
  { id: 3004, story_id: 30, line_index: 3, audio_file: '',
    swahili: 'Ninakusaidia kwa furaha. Usiwe na wasiwasi.',
    english: 'I am helping you with joy. Do not worry.' },
  { id: 3005, story_id: 30, line_index: 4, audio_file: '',
    swahili: 'Alinisaidia sana wakati nilikuwa mgonjwa.',
    english: 'He helped me a lot when I was sick.' },
  { id: 3006, story_id: 30, line_index: 5, audio_file: '',
    swahili: 'Tutakupa zawadi siku ya kuzaliwa kwako.',
    english: 'We will give you a gift on your birthday.' },
  { id: 3007, story_id: 30, line_index: 6, audio_file: '',
    swahili: 'Nilikuambia ukweli. Kwa nini huniamini?',
    english: 'I told you the truth. Why do you not believe me?' },
  { id: 3008, story_id: 30, line_index: 7, audio_file: '',
    swahili: 'Tutawasaidia wote. Hakuna atakayebaki nyuma.',
    english: 'We will help them all. No one will be left behind.' },
];

// ── Comprehension questions (2 per story, static — no DB needed) ───────────
// Keyed by story_id. Shown after the last story line before marking complete.
export const storyQuestions: Record<number, ComprehensionQuestion[]> = {
  1: [
    { id: 10101, story_id: 1, question_sw: 'Jina lake ni nani?', correct: 'Amina', options: ['Amina', 'Baraka', 'Fatuma', 'Ali'] },
    { id: 10102, story_id: 1, question_sw: 'Anaenda wapi sasa?', correct: 'Shuleni', options: ['Shuleni', 'Dukani', 'Nyumbani', 'Sokoni'] },
  ],
  2: [
    { id: 10201, story_id: 2, question_sw: 'Ni saa ngapi asubuhi?', correct: 'Saa tisa', options: ['Saa tisa', 'Saa kumi', 'Saa nne', 'Saa saba'] },
    { id: 10202, story_id: 2, question_sw: 'Vitabu vingapi amesoma mwaka huu?', correct: 'Saba', options: ['Saba', 'Kumi', 'Tano', 'Tatu'] },
  ],
  3: [
    { id: 10301, story_id: 3, question_sw: 'Wanaenda wapi asubuhi hii?', correct: 'Sokoni', options: ['Sokoni', 'Shuleni', 'Hospitali', 'Ofisini'] },
    { id: 10302, story_id: 3, question_sw: 'Nyumba yake iko karibu na nini?', correct: 'Mto', options: ['Mto', 'Mlima', 'Barabara', 'Duka'] },
  ],
  4: [
    { id: 10401, story_id: 4, question_sw: 'Nini kinauma sana?', correct: 'Kichwa', options: ['Kichwa', 'Mguu', 'Mkono', 'Sikio'] },
    { id: 10402, story_id: 4, question_sw: 'Daktari anasema nini?', correct: 'Pumzika na kunywa maji', options: ['Pumzika na kunywa maji', 'Nenda hospitali', 'Kula dawa', 'Lala mapema'] },
  ],
  5: [
    { id: 10501, story_id: 5, question_sw: 'Familia yake ni ndefu kiasi gani?', correct: 'Kubwa sana', options: ['Kubwa sana', 'Ndogo', 'Ya wastani', 'Moja tu'] },
    { id: 10502, story_id: 5, question_sw: 'Familia inakutana lini?', correct: 'Kila Jumapili', options: ['Kila Jumapili', 'Kila Jumamosi', 'Kila siku', 'Mwezi mzima'] },
  ],
  6: [
    { id: 10601, story_id: 6, question_sw: 'Kwa nini anafurahi?', correct: 'Amepata kazi mpya', options: ['Amepata kazi mpya', 'Amepata pesa', 'Amepona', 'Amekula vizuri'] },
    { id: 10602, story_id: 6, question_sw: 'Alikuwa na hali gani wiki iliyopita?', correct: 'Huzuni', options: ['Huzuni', 'Furaha', 'Hasira', 'Utulivu'] },
  ],
  7: [
    { id: 10701, story_id: 7, question_sw: 'Anakimbia kwa muda gani?', correct: 'Dakika ishirini', options: ['Dakika ishirini', 'Saa moja', 'Dakika kumi', 'Saa mbili'] },
    { id: 10702, story_id: 7, question_sw: 'Wanafanya nini jioni?', correct: 'Kula pamoja', options: ['Kula pamoja', 'Kusoma', 'Kucheza', 'Kulala'] },
  ],
  8: [
    { id: 10801, story_id: 8, question_sw: 'Anataka kwenda wapi?', correct: 'Pwani', options: ['Pwani', 'Mlimani', 'Sokoni', 'Msituni'] },
    { id: 10802, story_id: 8, question_sw: 'Watoto watasaidia kufanya nini?', correct: 'Kuosha vyombo', options: ['Kuosha vyombo', 'Kupika chakula', 'Kusafisha nyumba', 'Kununua chakula'] },
  ],
  9: [
    { id: 10901, story_id: 9, question_sw: 'Alikuwa mgonjwa kwa siku ngapi?', correct: 'Tatu', options: ['Tatu', 'Mbili', 'Tano', 'Moja'] },
    { id: 10902, story_id: 9, question_sw: 'Atasafiri kwenda wapi mwezi ujao?', correct: 'Dar es Salaam', options: ['Dar es Salaam', 'Nairobi', 'Mombasa', 'Arusha'] },
  ],
  10: [
    { id: 11001, story_id: 10, question_sw: 'Anataka gauni ya rangi gani?', correct: 'Bluu nyeupe', options: ['Bluu nyeupe', 'Jekundu', 'Njano', 'Kijani'] },
    { id: 11002, story_id: 10, question_sw: 'Ananunua gauni kwa nini?', correct: 'Harusi', options: ['Harusi', 'Sherehe', 'Kazi', 'Shule'] },
  ],
  11: [
    { id: 11101, story_id: 11, question_sw: 'Nyumba ina vyumba vingapi?', correct: 'Vinne', options: ['Vinne', 'Vitatu', 'Viwili', 'Vitano'] },
    { id: 11102, story_id: 11, question_sw: 'Sofa mpya ni ya rangi gani?', correct: 'Kahawia', options: ['Kahawia', 'Nyeupe', 'Nyekundu', 'Bluu'] },
  ],
  12: [
    { id: 11201, story_id: 12, question_sw: 'Anataka kupikwa nini?', correct: 'Ugali na sukuma wiki', options: ['Ugali na sukuma wiki', 'Nyama na wali', 'Samaki na mboga', 'Chai na mkate'] },
    { id: 11202, story_id: 12, question_sw: 'Chakula kitakuwa tayari lini?', correct: 'Saa moja', options: ['Saa moja', 'Dakika tano', 'Saa mbili', 'Saa tatu'] },
  ],
  13: [
    { id: 11301, story_id: 13, question_sw: 'Sherehe ya nini ni kesho?', correct: 'Harusi', options: ['Harusi', 'Siku ya kuzaliwa', 'Sikukuu', 'Mkutano'] },
    { id: 11302, story_id: 13, question_sw: 'Mke wake atavaa nini?', correct: 'Gauni jekundu', options: ['Gauni jekundu', 'Suruali ya bluu', 'Gauni nyeupe', 'Shati la njano'] },
  ],
  14: [
    { id: 11401, story_id: 14, question_sw: 'Hospitali iko umbali gani kwa miguu?', correct: 'Dakika tano', options: ['Dakika tano', 'Dakika kumi', 'Saa moja', 'Dakika ishirini'] },
    { id: 11402, story_id: 14, question_sw: 'Baada ya kugeuka kulia, duka liko wapi?', correct: 'Upande wa kushoto', options: ['Upande wa kushoto', 'Upande wa kulia', 'Mwisho wa barabara', 'Mbele yake'] },
  ],
  15: [
    { id: 11501, story_id: 15, question_sw: 'Ni usafiri gani wa bei nafuu zaidi?', correct: 'Basi', options: ['Basi', 'Treni', 'Teksi', 'Ndege'] },
    { id: 11502, story_id: 15, question_sw: 'Treni inaondoka saa ngapi?', correct: 'Saa saba asubuhi', options: ['Saa saba asubuhi', 'Saa nne asubuhi', 'Saa kumi asubuhi', 'Saa tisa asubuhi'] },
  ],
  16: [
    { id: 11601, story_id: 16, question_sw: 'Bei ya kwanza ya nguo ilikuwa ngapi?', correct: 'Shilingi elfu tano', options: ['Shilingi elfu tano', 'Shilingi elfu tatu', 'Shilingi elfu nne', 'Shilingi elfu mbili'] },
    { id: 11602, story_id: 16, question_sw: 'Je, wanakubali pesa ya aina gani?', correct: 'M-Pesa', options: ['M-Pesa', 'Pesa taslimu tu', 'Kadi ya benki', 'Hundi'] },
  ],
  17: [
    { id: 11701, story_id: 17, question_sw: 'Amekuwa mgonjwa kwa siku ngapi?', correct: 'Mbili', options: ['Mbili', 'Tatu', 'Moja', 'Nne'] },
    { id: 11702, story_id: 17, question_sw: 'Anaambiwa kufanya nini?', correct: 'Kaa nyumbani', options: ['Kaa nyumbani', 'Nenda kazini', 'Safiri', 'Nenda shuleni'] },
  ],
  18: [
    { id: 11801, story_id: 18, question_sw: 'Ofisi iko ghorofa ya ngapi?', correct: 'Ya tatu', options: ['Ya tatu', 'Ya kwanza', 'Ya pili', 'Ya nne'] },
    { id: 11802, story_id: 18, question_sw: 'Mshahara utaingia lini?', correct: 'Mwezi ujao', options: ['Mwezi ujao', 'Wiki ijayo', 'Leo', 'Kesho'] },
  ],
  19: [
    { id: 11901, story_id: 19, question_sw: 'Itakuwa na mvua lini?', correct: 'Mchana', options: ['Mchana', 'Asubuhi', 'Jioni', 'Usiku'] },
    { id: 11902, story_id: 19, question_sw: 'Watakwenda wapi asubuhi?', correct: 'Pwani', options: ['Pwani', 'Msituni', 'Mlimani', 'Sokoni'] },
  ],
  20: [
    { id: 12001, story_id: 20, question_sw: 'Anahitaji nini?', correct: 'Msaada kidogo', options: ['Msaada kidogo', 'Pesa nyingi', 'Chakula', 'Pumziko'] },
    { id: 12002, story_id: 20, question_sw: 'Nani atamfundisha?', correct: 'Mwenzake wa kazi', options: ['Mwenzake wa kazi', 'Mwalimu wa shule', 'Daktari', 'Mama yake'] },
  ],
};
