import type { Word, Lesson } from '../../types/content';

// Expanded words & lessons: doubles each unit from 20→40 words and 4→8 lessons.
// Words IDs 801–1600, Lessons IDs 161–320.

export const expandedWords: Word[] = [
  // ── Unit 1: Greetings (801–820) ─────────────────────────────────────
  { id: 801, swahili: 'Kwaheri', english: 'Goodbye', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Kwaheri rafiki yangu.', example_en: 'Goodbye my friend.' },
  { id: 802, swahili: 'Hujambo', english: 'How are you? (singular)', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Hujambo? Habari za leo?', example_en: 'How are you? News of today?' },
  { id: 803, swahili: 'Hamjambo', english: 'How are you? (plural)', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Hamjambo wanafunzi?', example_en: 'How are you students?' },
  { id: 804, swahili: 'Salama', english: 'Peace / Safe', audio_file: '', unit_id: 1, pos: 'adjective', example_sw: 'Tumefika salama nyumbani.', example_en: 'We arrived home safely.' },
  { id: 805, swahili: 'Mambo', english: "What's up? (slang)", audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Mambo vipi kaka?', example_en: "What's up brother?" },
  { id: 806, swahili: 'Safi', english: 'Fine / Clean (slang)', audio_file: '', unit_id: 1, pos: 'adjective', example_sw: 'Mambo? — Safi kabisa!', example_en: "What's up? — Totally fine!" },
  { id: 807, swahili: 'Shikamoo', english: 'Greeting to elder', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Shikamoo babu, habari zako?', example_en: 'Greetings grandfather, how are you?' },
  { id: 808, swahili: 'Marahaba', english: 'Response to shikamoo', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Marahaba mwanangu, karibu sana.', example_en: 'I accept your greeting, my child, welcome.' },
  { id: 809, swahili: 'U hali gani?', english: 'How are you? (coastal)', audio_file: '', unit_id: 1, pos: 'phrase', example_sw: 'U hali gani leo mzee?', example_en: 'How are you today elder?' },
  { id: 810, swahili: 'Njema', english: 'Good / Well', audio_file: '', unit_id: 1, pos: 'adjective', example_sw: 'Habari zako? — Njema.', example_en: 'How are you? — Good.' },
  { id: 811, swahili: 'Nakupenda', english: 'I love you', audio_file: '', unit_id: 1, pos: 'phrase', example_sw: 'Nakupenda mama yangu.', example_en: 'I love you my mother.' },
  { id: 812, swahili: 'Hongera', english: 'Congratulations', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Hongera kwa mtihani wako!', example_en: 'Congratulations on your exam!' },
  { id: 813, swahili: 'Pole', english: 'Sorry / Sympathy', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Pole na kazi yako ngumu.', example_en: 'Sorry about your hard work.' },
  { id: 814, swahili: 'Sawa', english: 'Okay / Alright', audio_file: '', unit_id: 1, pos: 'adverb', example_sw: 'Sawa, tutaonana kesho.', example_en: 'Okay, we will see each other tomorrow.' },
  { id: 815, swahili: 'Sijambo', english: 'I am fine (response)', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Hujambo? — Sijambo, asante.', example_en: 'How are you? — I am fine, thank you.' },
  { id: 816, swahili: 'Hatujambo', english: 'We are fine (response)', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Hamjambo? — Hatujambo.', example_en: 'How are you all? — We are fine.' },
  { id: 817, swahili: 'Karibuni', english: 'Welcome (plural)', audio_file: '', unit_id: 1, pos: 'interjection', example_sw: 'Karibuni nyumbani wageni wote.', example_en: 'Welcome home all guests.' },
  { id: 818, swahili: 'Tutaonana', english: 'See you later', audio_file: '', unit_id: 1, pos: 'phrase', example_sw: 'Tutaonana kesho asubuhi.', example_en: 'See you tomorrow morning.' },
  { id: 819, swahili: 'Nisaidie', english: 'Help me', audio_file: '', unit_id: 1, pos: 'phrase', example_sw: 'Tafadhali nisaidie kubeba mzigo huu.', example_en: 'Please help me carry this load.' },
  { id: 820, swahili: 'Jioni njema', english: 'Good evening', audio_file: '', unit_id: 1, pos: 'phrase', example_sw: 'Jioni njema, tutaonana kesho.', example_en: 'Good evening, see you tomorrow.' },

  // ── Unit 2: Numbers & Time (821–840) ────────────────────────────────
  { id: 821, swahili: 'Saa ngapi?', english: 'What time is it?', audio_file: '', unit_id: 2, pos: 'phrase', example_sw: 'Saa ngapi sasa hivi?', example_en: 'What time is it right now?' },
  { id: 822, swahili: 'Dakika', english: 'Minute', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Subiri dakika tano tafadhali.', example_en: 'Wait five minutes please.' },
  { id: 823, swahili: 'Sekunde', english: 'Second (time)', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Alikimbia mita mia moja kwa sekunde kumi.', example_en: 'He ran one hundred metres in ten seconds.' },
  { id: 824, swahili: 'Siku', english: 'Day', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Siku saba zinafanya wiki moja.', example_en: 'Seven days make one week.' },
  { id: 825, swahili: 'Mchana', english: 'Daytime / Afternoon', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Mchana jua ni kali sana.', example_en: 'During the day the sun is very hot.' },
  { id: 826, swahili: 'Alfajiri', english: 'Dawn / Early morning', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Ninaamka alfajiri kila siku.', example_en: 'I wake up at dawn every day.' },
  { id: 827, swahili: 'Adhuhuri', english: 'Midday / Noon', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Tunakula adhuhuri pamoja.', example_en: 'We eat lunch together.' },
  { id: 828, swahili: 'Alasiri', english: 'Late afternoon', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Alasiri tunapumzika kidogo.', example_en: 'In the late afternoon we rest a little.' },
  { id: 829, swahili: 'Magharibi', english: 'Sunset / West', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Jua linazama magharibi.', example_en: 'The sun sets in the west.' },
  { id: 830, swahili: 'Usiku wa manane', english: 'Midnight', audio_file: '', unit_id: 2, pos: 'phrase', example_sw: 'Usiku wa manane kuna utulivu.', example_en: 'At midnight there is calm.' },
  { id: 831, swahili: 'Saa moja', english: "Seven o'clock (Swahili time)", audio_file: '', unit_id: 2, pos: 'phrase', example_sw: 'Saa moja asubuhi tunaamka.', example_en: 'At seven in the morning we wake up.' },
  { id: 832, swahili: 'Saa sita', english: "Twelve o'clock (Swahili time)", audio_file: '', unit_id: 2, pos: 'phrase', example_sw: 'Saa sita mchana tunakula.', example_en: 'At twelve noon we eat.' },
  { id: 833, swahili: 'Nusu saa', english: 'Half an hour', audio_file: '', unit_id: 2, pos: 'phrase', example_sw: 'Subiri nusu saa tu.', example_en: 'Wait just half an hour.' },
  { id: 834, swahili: 'Robo saa', english: 'Quarter of an hour', audio_file: '', unit_id: 2, pos: 'phrase', example_sw: 'Robo saa imepita tangu aondoke.', example_en: 'A quarter of an hour has passed since he left.' },
  { id: 835, swahili: 'Mara', english: 'Time / Instance', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Nimekuja hapa mara tatu.', example_en: 'I have come here three times.' },
  { id: 836, swahili: 'Kipindi', english: 'Period / Season', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Kipindi cha mvua kimeanza.', example_en: 'The rainy season has started.' },
  { id: 837, swahili: 'Zamani', english: 'Long ago / In the past', audio_file: '', unit_id: 2, pos: 'adverb', example_sw: 'Zamani watu walitembea kwa miguu.', example_en: 'Long ago people walked on foot.' },
  { id: 838, swahili: 'Sasa', english: 'Now', audio_file: '', unit_id: 2, pos: 'adverb', example_sw: 'Sasa ni wakati wa kulala.', example_en: 'Now it is time to sleep.' },
  { id: 839, swahili: 'Baadaye', english: 'Later / Afterwards', audio_file: '', unit_id: 2, pos: 'adverb', example_sw: 'Tutaonana baadaye mchana.', example_en: 'We will meet later in the afternoon.' },
  { id: 840, swahili: 'Muda', english: 'Time / Duration', audio_file: '', unit_id: 2, pos: 'noun', example_sw: 'Muda wa kusoma umefika.', example_en: 'The time to study has arrived.' },

  // ── Unit 3: Daily Life (841–860) ─────────────────────────────────────
  { id: 841, swahili: 'Barabara kuu', english: 'Main road / Highway', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Barabara kuu ina magari mengi.', example_en: 'The highway has many cars.' },
  { id: 842, swahili: 'Kivuko', english: 'Ferry / Crossing', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Kivuko kinavuka mto kila saa.', example_en: 'The ferry crosses the river every hour.' },
  { id: 843, swahili: 'Kibanda', english: 'Kiosk / Stall', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Ninanunua mboga kwenye kibanda.', example_en: 'I buy vegetables at the kiosk.' },
  { id: 844, swahili: 'Gereji', english: 'Garage', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Gari langu liko gerejini kurekebishwa.', example_en: 'My car is at the garage being repaired.' },
  { id: 845, swahili: 'Uwanja', english: 'Field / Open ground', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Watoto wanacheza uwanjani.', example_en: 'Children are playing on the field.' },
  { id: 846, swahili: 'Bustani ya umma', english: 'Public garden', audio_file: '', unit_id: 3, pos: 'phrase', example_sw: 'Tunatembea kwenye bustani Jumapili.', example_en: 'We walk in the garden on Sunday.' },
  { id: 847, swahili: 'Jumba la kumbukumbu', english: 'Museum', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Jumba la kumbukumbu lina historia nyingi.', example_en: 'The museum has a lot of history.' },
  { id: 848, swahili: 'Sinema', english: 'Cinema', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Tunakwenda sinema jioni hii.', example_en: 'We are going to the cinema this evening.' },
  { id: 849, swahili: 'Mkahawa', english: 'Restaurant / Cafe', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Tutakula mkahawani leo.', example_en: 'We will eat at the restaurant today.' },
  { id: 850, swahili: 'Huduma', english: 'Service', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Huduma katika hoteli hii ni nzuri.', example_en: 'The service at this hotel is good.' },
  { id: 851, swahili: 'Kiwanda', english: 'Factory', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Kiwanda hiki kinazalisha viatu.', example_en: 'This factory produces shoes.' },
  { id: 852, swahili: 'Ghorofa', english: 'Floor / Storey', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Ofisi ziko ghorofa ya tano.', example_en: 'The offices are on the fifth floor.' },
  { id: 853, swahili: 'Ukumbi', english: 'Hall / Lounge', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Sherehe itafanyika ukumbini.', example_en: 'The celebration will take place in the hall.' },
  { id: 854, swahili: 'Bwawa', english: 'Pool / Pond', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Bwawa la kuogelea liko nyuma ya hoteli.', example_en: 'The swimming pool is behind the hotel.' },
  { id: 855, swahili: 'Taa', english: 'Light / Lamp', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Washa taa, usiku umeingia.', example_en: 'Turn on the light, night has fallen.' },
  { id: 856, swahili: 'Stesheni ya basi', english: 'Bus station', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Stesheni ya basi iko karibu.', example_en: 'The bus station is nearby.' },
  { id: 857, swahili: 'Soko kuu', english: 'Main market', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Bei katika soko kuu ni nafuu.', example_en: 'Prices at the main market are cheap.' },
  { id: 858, swahili: 'Kituo cha afya', english: 'Health centre', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Kituo cha afya kinatoa huduma bure.', example_en: 'The health centre provides free service.' },
  { id: 859, swahili: 'Posta', english: 'Post office', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Nenda posta kutuma barua.', example_en: 'Go to the post office to send a letter.' },
  { id: 860, swahili: 'Kituo cha polisi', english: 'Police station', audio_file: '', unit_id: 3, pos: 'noun', example_sw: 'Kituo cha polisi kipo mtaani humu.', example_en: 'The police station is on this street.' },

  // ── Unit 4: The Body (861–880) ───────────────────────────────────────
  { id: 861, swahili: 'Kiganja', english: 'Palm (of hand)', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Kiganja chake ni laini.', example_en: 'His palm is smooth.' },
  { id: 862, swahili: 'Kisigino', english: 'Heel', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Kisigino chake kinauma baada ya kutembea.', example_en: 'His heel hurts after walking.' },
  { id: 863, swahili: 'Kiwiko', english: 'Elbow', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Aligonga kiwiko chake mezani.', example_en: 'He hit his elbow on the table.' },
  { id: 864, swahili: 'Kifundo', english: 'Wrist / Knuckle', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Kifundo chake kimevimba.', example_en: 'His wrist is swollen.' },
  { id: 865, swahili: 'Kope', english: 'Eyelash', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Kope zake ni ndefu na nzuri.', example_en: 'Her eyelashes are long and beautiful.' },
  { id: 866, swahili: 'Nyusi', english: 'Eyebrow', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Nyusi zake ni nyeusi na nzito.', example_en: 'Her eyebrows are dark and thick.' },
  { id: 867, swahili: 'Taya', english: 'Jaw', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Taya lake linauma baada ya upasuaji.', example_en: 'His jaw hurts after the surgery.' },
  { id: 868, swahili: 'Kidevu', english: 'Chin', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Kidevu chake kina ndevu kidogo.', example_en: 'His chin has a little beard.' },
  { id: 869, swahili: 'Paji', english: 'Forehead', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Paji lake lina jasho.', example_en: 'His forehead has sweat.' },
  { id: 870, swahili: 'Shavu', english: 'Cheek', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Mashavu yake ni mekundu.', example_en: 'Her cheeks are red.' },
  { id: 871, swahili: 'Ufizi', english: 'Gums', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Ufizi wangu unavuja damu.', example_en: 'My gums are bleeding.' },
  { id: 872, swahili: 'Ulimi', english: 'Tongue', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Ulimi unaonja ladha ya chakula.', example_en: 'The tongue tastes the flavour of food.' },
  { id: 873, swahili: 'Koo', english: 'Throat', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Koo langu linauma, nahitaji dawa.', example_en: 'My throat hurts, I need medicine.' },
  { id: 874, swahili: 'Mapafu', english: 'Lungs', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Mapafu yanasafisha hewa.', example_en: 'The lungs clean the air.' },
  { id: 875, swahili: 'Ubongo', english: 'Brain', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Ubongo unaongoza mwili wote.', example_en: 'The brain controls the whole body.' },
  { id: 876, swahili: 'Mifupa', english: 'Bones', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Maziwa yanaimarisha mifupa.', example_en: 'Milk strengthens bones.' },
  { id: 877, swahili: 'Misuli', english: 'Muscles', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Mazoezi yanajenga misuli.', example_en: 'Exercise builds muscles.' },
  { id: 878, swahili: 'Nyayo', english: 'Footprints / Soles', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Nyayo zinaonekana mchangani.', example_en: 'Footprints are visible in the sand.' },
  { id: 879, swahili: 'Kiganja cha mguu', english: 'Sole of foot', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Kiganja cha mguu wake kina vidonda.', example_en: 'The sole of his foot has sores.' },
  { id: 880, swahili: 'Kiwiliwili', english: 'Torso / Trunk', audio_file: '', unit_id: 4, pos: 'noun', example_sw: 'Kiwiliwili chake ni kipana.', example_en: 'His torso is broad.' },

  // ── Unit 5: Family (881–900) ─────────────────────────────────────────
  { id: 881, swahili: 'Shemeji', english: 'Brother/Sister-in-law', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Shemeji yangu anaishi Arusha.', example_en: 'My brother-in-law lives in Arusha.' },
  { id: 882, swahili: 'Mkwe', english: 'Father/Mother-in-law', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Mkwe wangu ana shamba kubwa.', example_en: 'My father-in-law has a large farm.' },
  { id: 883, swahili: 'Mchumba', english: 'Fiancé(e)', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Mchumba wangu ni mhandisi.', example_en: 'My fiancé is an engineer.' },
  { id: 884, swahili: 'Mjukuu', english: 'Grandchild', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Wajukuu wangu wanapenda kucheza.', example_en: 'My grandchildren love to play.' },
  { id: 885, swahili: 'Mlezi', english: 'Guardian / Caretaker', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Mlezi wangu alinilea vizuri.', example_en: 'My guardian raised me well.' },
  { id: 886, swahili: 'Mjane', english: 'Widow(er)', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Mjane yule anafanya kazi kwa bidii.', example_en: 'That widow works very hard.' },
  { id: 887, swahili: 'Mzee', english: 'Elder / Old person', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Mzee wetu ana hekima kubwa.', example_en: 'Our elder has great wisdom.' },
  { id: 888, swahili: 'Kijana', english: 'Youth / Young person', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Vijana wanapaswa kusoma.', example_en: 'Youths should study.' },
  { id: 889, swahili: 'Kizazi', english: 'Generation', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Kizazi kipya kina matumaini.', example_en: 'The new generation has hope.' },
  { id: 890, swahili: 'Urithi', english: 'Inheritance', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Urithi wa baba uligawanywa kwa watoto.', example_en: "Father's inheritance was divided among the children." },
  { id: 891, swahili: 'Talaka', english: 'Divorce', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Talaka inaumiza familia.', example_en: 'Divorce hurts the family.' },
  { id: 892, swahili: 'Mahari', english: 'Bride price / Dowry', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Mahari yalilipwa jana.', example_en: 'The dowry was paid yesterday.' },
  { id: 893, swahili: 'Arusi', english: 'Wedding celebration', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Arusi ilikuwa na wageni wengi.', example_en: 'The wedding celebration had many guests.' },
  { id: 894, swahili: 'Ujirani', english: 'Neighbourliness', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Ujirani mwema unaleta amani.', example_en: 'Good neighbourliness brings peace.' },
  { id: 895, swahili: 'Jamaa', english: 'Relative / Kin', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Jamaa zangu wote wamekuja sikukuu.', example_en: 'All my relatives have come for the holiday.' },
  { id: 896, swahili: 'Kipenzi', english: 'Darling / Beloved', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Kipenzi changu kimenipa zawadi.', example_en: 'My darling has given me a gift.' },
  { id: 897, swahili: 'Yatima', english: 'Orphan', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Watoto yatima wanahitaji msaada.', example_en: 'Orphan children need help.' },
  { id: 898, swahili: 'Nasaba', english: 'Lineage / Ancestry', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Nasaba yetu inatoka mkoani.', example_en: 'Our lineage comes from the region.' },
  { id: 899, swahili: 'Mfiwa', english: 'Bereaved person', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Mfiwa alipewa pole na marafiki.', example_en: 'The bereaved was given condolences by friends.' },
  { id: 900, swahili: 'Ukoo mkubwa', english: 'Extended clan', audio_file: '', unit_id: 5, pos: 'noun', example_sw: 'Ukoo wetu mkubwa unakutana kila mwaka.', example_en: 'Our extended clan meets every year.' },

  // ── Unit 6: Emotions (901–920) ───────────────────────────────────────
  { id: 901, swahili: 'Sikitiko', english: 'Regret / Sorrow', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Sikitiko lake lilikuwa kubwa.', example_en: 'His regret was great.' },
  { id: 902, swahili: 'Hamu', english: 'Eagerness / Desire', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Nina hamu ya kwenda nyumbani.', example_en: 'I am eager to go home.' },
  { id: 903, swahili: 'Kusitasita', english: 'Hesitation / Doubt', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Kusitasita kwake kunaonekana.', example_en: 'His hesitation is visible.' },
  { id: 904, swahili: 'Ujasiri', english: 'Courage / Bravery', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Ujasiri wake ulituokoa.', example_en: 'His courage saved us.' },
  { id: 905, swahili: 'Woga', english: 'Cowardice / Fearfulness', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Woga wake unamzuia kusema.', example_en: 'His fearfulness stops him from speaking.' },
  { id: 906, swahili: 'Unyenyekevu', english: 'Humility', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Unyenyekevu wake unavutia watu.', example_en: 'His humility attracts people.' },
  { id: 907, swahili: 'Kiburi', english: 'Arrogance (negative pride)', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Kiburi chake kinamfanya apoteze marafiki.', example_en: 'His arrogance makes him lose friends.' },
  { id: 908, swahili: 'Upweke', english: 'Loneliness', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Upweke unamuumiza mzee huyo.', example_en: 'Loneliness hurts that old person.' },
  { id: 909, swahili: 'Uchungu', english: 'Bitterness / Pain', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Uchungu wa kufiwa ni mkubwa.', example_en: 'The bitterness of bereavement is great.' },
  { id: 910, swahili: 'Ushujaa', english: 'Heroism', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Ushujaa wake ulitambuliwa na wote.', example_en: 'His heroism was recognized by all.' },
  { id: 911, swahili: 'Ridhaa', english: 'Contentment', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Anaishi kwa ridhaa na maisha yake.', example_en: 'He lives with contentment about his life.' },
  { id: 912, swahili: 'Kukata tamaa', english: 'Despair / Giving up', audio_file: '', unit_id: 6, pos: 'phrase', example_sw: 'Usikate tamaa, Mungu yupo.', example_en: 'Do not despair, God is present.' },
  { id: 913, swahili: 'Kutia moyo', english: 'To encourage', audio_file: '', unit_id: 6, pos: 'phrase', example_sw: 'Maneno yake ya kutia moyo yalitusaidia.', example_en: 'His words of encouragement helped us.' },
  { id: 914, swahili: 'Urafiki', english: 'Friendship', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Urafiki wetu umedumu kwa miaka mingi.', example_en: 'Our friendship has lasted for many years.' },
  { id: 915, swahili: 'Wivu wa mapenzi', english: 'Romantic jealousy', audio_file: '', unit_id: 6, pos: 'phrase', example_sw: 'Wivu wa mapenzi unaharibu uhusiano.', example_en: 'Romantic jealousy destroys relationships.' },
  { id: 916, swahili: 'Lawama', english: 'Blame / Reproach', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Lawama hazina faida sasa.', example_en: 'Blame is useless now.' },
  { id: 917, swahili: 'Huzuni kubwa', english: 'Deep sadness / Grief', audio_file: '', unit_id: 6, pos: 'phrase', example_sw: 'Huzuni kubwa ilimfunika baada ya msiba.', example_en: 'Deep sadness covered him after the tragedy.' },
  { id: 918, swahili: 'Kusamehe', english: 'To forgive', audio_file: '', unit_id: 6, pos: 'verb', example_sw: 'Nimesamehe wote walionikosea.', example_en: 'I have forgiven all who wronged me.' },
  { id: 919, swahili: 'Shukrani', english: 'Gratitude / Thanks', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Shukrani zangu kwako hazina mwisho.', example_en: 'My gratitude to you is endless.' },
  { id: 920, swahili: 'Upinzani', english: 'Opposition / Resistance', audio_file: '', unit_id: 6, pos: 'noun', example_sw: 'Upinzani wao ulishindikana.', example_en: 'Their opposition failed.' },

  // ── Unit 7: Action Verbs I (921–940) ─────────────────────────────────
  { id: 921, swahili: 'Kuketi', english: 'To sit down', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Keti chini tafadhali.', example_en: 'Sit down please.' },
  { id: 922, swahili: 'Kuinuka', english: 'To stand up / Rise', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Inuka uende kazini.', example_en: 'Get up and go to work.' },
  { id: 923, swahili: 'Kucheka', english: 'To laugh', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Walicheka hadi machozi.', example_en: 'They laughed until tears came.' },
  { id: 924, swahili: 'Kulia', english: 'To cry / Weep', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Mtoto analia kwa njaa.', example_en: 'The child is crying from hunger.' },
  { id: 925, swahili: 'Kupumua', english: 'To breathe', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Pumua kwa kina kabisa.', example_en: 'Breathe in deeply.' },
  { id: 926, swahili: 'Kukohoa', english: 'To cough', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Anakohoa sana, ana homa.', example_en: 'He is coughing a lot, he has a fever.' },
  { id: 927, swahili: 'Kupiga chafya', english: 'To sneeze', audio_file: '', unit_id: 7, pos: 'phrase', example_sw: 'Alipiga chafya mara tatu.', example_en: 'He sneezed three times.' },
  { id: 928, swahili: 'Kugeuka', english: 'To turn', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Geuka kushoto mwisho wa barabara.', example_en: 'Turn left at the end of the road.' },
  { id: 929, swahili: 'Kuinama', english: 'To bend down', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Inama uokote kalamu yako.', example_en: 'Bend down and pick up your pen.' },
  { id: 930, swahili: 'Kuruka', english: 'To jump / Fly', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Mtoto anaruka juu kwa furaha.', example_en: 'The child is jumping up with joy.' },
  { id: 931, swahili: 'Kuanguka', english: 'To fall', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Alianguka chini na kuumia mguu.', example_en: 'He fell down and hurt his leg.' },
  { id: 932, swahili: 'Kupanda', english: 'To climb / Go up', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Anapanda mlima kila mwaka.', example_en: 'He climbs the mountain every year.' },
  { id: 933, swahili: 'Kushuka', english: 'To descend / Go down', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Shuka ngazi polepole.', example_en: 'Go down the stairs slowly.' },
  { id: 934, swahili: 'Kuvuta', english: 'To pull / Drag', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Vuta mlango ufunge.', example_en: 'Pull the door closed.' },
  { id: 935, swahili: 'Kusukuma', english: 'To push', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Sukuma gari hadi gerejini.', example_en: 'Push the car to the garage.' },
  { id: 936, swahili: 'Kuinua', english: 'To lift / Raise', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Inua mkono wako.', example_en: 'Raise your hand.' },
  { id: 937, swahili: 'Kutupa', english: 'To throw', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Tupa mpira kwangu!', example_en: 'Throw the ball to me!' },
  { id: 938, swahili: 'Kushika', english: 'To hold / Catch', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Shika mkono wangu.', example_en: 'Hold my hand.' },
  { id: 939, swahili: 'Kufunga', english: 'To close / Tie', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Funga mlango kabla ya kulala.', example_en: 'Close the door before sleeping.' },
  { id: 940, swahili: 'Kufungua', english: 'To open / Untie', audio_file: '', unit_id: 7, pos: 'verb', example_sw: 'Fungua dirisha kupata hewa safi.', example_en: 'Open the window for fresh air.' },

  // ── Unit 8: Action Verbs II (941–960) ────────────────────────────────
  { id: 941, swahili: 'Kukubali', english: 'To accept / Agree', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Nakubali ombi lako.', example_en: 'I accept your request.' },
  { id: 942, swahili: 'Kukataa', english: 'To refuse / Reject', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Alikataa kuja na sisi.', example_en: 'He refused to come with us.' },
  { id: 943, swahili: 'Kutumia', english: 'To use', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Tumia kalamu hii kuandika.', example_en: 'Use this pen to write.' },
  { id: 944, swahili: 'Kujaribu', english: 'To try / Attempt', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Jaribu tena, utafanikiwa.', example_en: 'Try again, you will succeed.' },
  { id: 945, swahili: 'Kufanikiwa', english: 'To succeed', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Amefanikiwa katika maisha yake.', example_en: 'He has succeeded in his life.' },
  { id: 946, swahili: 'Kushindwa', english: 'To fail', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Alijaribu lakini alishindwa.', example_en: 'He tried but he failed.' },
  { id: 947, swahili: 'Kutarajia', english: 'To expect / Hope', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Natarajia kuona matokeo mazuri.', example_en: 'I expect to see good results.' },
  { id: 948, swahili: 'Kuamini', english: 'To believe / Trust', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Ninaamini utaweza.', example_en: 'I believe you will be able.' },
  { id: 949, swahili: 'Kushuku', english: 'To suspect / Doubt', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Nashuku kuwa si kweli.', example_en: 'I suspect it is not true.' },
  { id: 950, swahili: 'Kulinganisha', english: 'To compare', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Linganisha bei kabla ya kununua.', example_en: 'Compare prices before buying.' },
  { id: 951, swahili: 'Kuamua', english: 'To decide', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Ameamua kwenda kusoma nje.', example_en: 'He has decided to study abroad.' },
  { id: 952, swahili: 'Kuchagua', english: 'To choose', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Chagua kitabu unachotaka.', example_en: 'Choose the book you want.' },
  { id: 953, swahili: 'Kuhifadhi', english: 'To store / Preserve', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Hifadhi chakula jokofu.', example_en: 'Store the food in the fridge.' },
  { id: 954, swahili: 'Kugawa', english: 'To divide / Share', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Gawa chakula kwa watoto wote.', example_en: 'Share the food among all children.' },
  { id: 955, swahili: 'Kuongeza', english: 'To add / Increase', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Ongeza chumvi kidogo.', example_en: 'Add a little salt.' },
  { id: 956, swahili: 'Kupunguza', english: 'To reduce / Decrease', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Punguza sukari katika chai.', example_en: 'Reduce the sugar in the tea.' },
  { id: 957, swahili: 'Kuthibitisha', english: 'To confirm / Prove', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Thibitisha nafasi yako ya safari.', example_en: 'Confirm your travel reservation.' },
  { id: 958, swahili: 'Kutangaza', english: 'To announce', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Serikali ilitangaza likizo.', example_en: 'The government announced a holiday.' },
  { id: 959, swahili: 'Kuomba', english: 'To request / Pray', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Naomba msaada wako.', example_en: 'I request your help.' },
  { id: 960, swahili: 'Kuahirisha', english: 'To postpone', audio_file: '', unit_id: 8, pos: 'verb', example_sw: 'Mkutano umeahirishwa hadi kesho.', example_en: 'The meeting has been postponed until tomorrow.' },
];

export const expandedLessons: Lesson[] = [
  { id: 161, unit_id: 1, title: 'Polite Expressions', lesson_index: 4, exercise_count: 10 },
  { id: 162, unit_id: 1, title: 'Getting to Know Someone', lesson_index: 5, exercise_count: 10 },
  { id: 163, unit_id: 1, title: 'Saying Goodbye', lesson_index: 6, exercise_count: 10 },
  { id: 164, unit_id: 1, title: 'Greetings Review II', lesson_index: 7, exercise_count: 10 },
  { id: 165, unit_id: 2, title: 'Telling the Time', lesson_index: 4, exercise_count: 10 },
  { id: 166, unit_id: 2, title: 'Times of Day', lesson_index: 5, exercise_count: 10 },
  { id: 167, unit_id: 2, title: 'Seasons & Periods', lesson_index: 6, exercise_count: 10 },
  { id: 168, unit_id: 2, title: 'Time Review II', lesson_index: 7, exercise_count: 10 },
  { id: 169, unit_id: 3, title: 'Around Town', lesson_index: 4, exercise_count: 10 },
  { id: 170, unit_id: 3, title: 'Services & Places', lesson_index: 5, exercise_count: 10 },
  { id: 171, unit_id: 3, title: 'Buildings & Structures', lesson_index: 6, exercise_count: 10 },
  { id: 172, unit_id: 3, title: 'Daily Life Review II', lesson_index: 7, exercise_count: 10 },
  { id: 173, unit_id: 4, title: 'Hands & Feet', lesson_index: 4, exercise_count: 10 },
  { id: 174, unit_id: 4, title: 'Face Details', lesson_index: 5, exercise_count: 10 },
  { id: 175, unit_id: 4, title: 'Internal Organs', lesson_index: 6, exercise_count: 10 },
  { id: 176, unit_id: 4, title: 'Body Review II', lesson_index: 7, exercise_count: 10 },
  { id: 177, unit_id: 5, title: 'In-Laws & Extended', lesson_index: 4, exercise_count: 10 },
  { id: 178, unit_id: 5, title: 'Life Stages', lesson_index: 5, exercise_count: 10 },
  { id: 179, unit_id: 5, title: 'Family Traditions', lesson_index: 6, exercise_count: 10 },
  { id: 180, unit_id: 5, title: 'Family Review II', lesson_index: 7, exercise_count: 10 },
  { id: 181, unit_id: 6, title: 'Complex Feelings', lesson_index: 4, exercise_count: 10 },
  { id: 182, unit_id: 6, title: 'Character Traits', lesson_index: 5, exercise_count: 10 },
  { id: 183, unit_id: 6, title: 'States of Mind', lesson_index: 6, exercise_count: 10 },
  { id: 184, unit_id: 6, title: 'Emotions Review II', lesson_index: 7, exercise_count: 10 },
  { id: 185, unit_id: 7, title: 'Body Actions', lesson_index: 4, exercise_count: 10 },
  { id: 186, unit_id: 7, title: 'Movement Verbs II', lesson_index: 5, exercise_count: 10 },
  { id: 187, unit_id: 7, title: 'Push & Pull Verbs', lesson_index: 6, exercise_count: 10 },
  { id: 188, unit_id: 7, title: 'Action Verbs Review II', lesson_index: 7, exercise_count: 10 },
  { id: 189, unit_id: 8, title: 'Decision Verbs', lesson_index: 4, exercise_count: 10 },
  { id: 190, unit_id: 8, title: 'Belief & Doubt', lesson_index: 5, exercise_count: 10 },
  { id: 191, unit_id: 8, title: 'Process Verbs', lesson_index: 6, exercise_count: 10 },
  { id: 192, unit_id: 8, title: 'Verbs Review II', lesson_index: 7, exercise_count: 10 },
  { id: 193, unit_id: 9, title: 'Tense Practice', lesson_index: 4, exercise_count: 10 },
  { id: 194, unit_id: 9, title: 'Conditional Forms', lesson_index: 5, exercise_count: 10 },
  { id: 195, unit_id: 9, title: 'Habitual Actions', lesson_index: 6, exercise_count: 10 },
  { id: 196, unit_id: 9, title: 'Verb Tenses Review II', lesson_index: 7, exercise_count: 10 },
  { id: 197, unit_id: 10, title: 'More Colours', lesson_index: 4, exercise_count: 10 },
  { id: 198, unit_id: 10, title: 'Describing People', lesson_index: 5, exercise_count: 10 },
  { id: 199, unit_id: 10, title: 'Describing Objects', lesson_index: 6, exercise_count: 10 },
  { id: 200, unit_id: 10, title: 'Adjectives Review II', lesson_index: 7, exercise_count: 10 },
  { id: 201, unit_id: 11, title: 'Outdoor Areas', lesson_index: 4, exercise_count: 10 },
  { id: 202, unit_id: 11, title: 'Household Chores', lesson_index: 5, exercise_count: 10 },
  { id: 203, unit_id: 11, title: 'Home Improvement', lesson_index: 6, exercise_count: 10 },
  { id: 204, unit_id: 11, title: 'Home Review II', lesson_index: 7, exercise_count: 10 },
  { id: 205, unit_id: 12, title: 'More Ingredients', lesson_index: 4, exercise_count: 10 },
  { id: 206, unit_id: 12, title: 'Cooking Methods', lesson_index: 5, exercise_count: 10 },
  { id: 207, unit_id: 12, title: 'Eating Out', lesson_index: 6, exercise_count: 10 },
  { id: 208, unit_id: 12, title: 'Food Review II', lesson_index: 7, exercise_count: 10 },
  { id: 209, unit_id: 13, title: 'Footwear & Bags', lesson_index: 4, exercise_count: 10 },
  { id: 210, unit_id: 13, title: 'Fabrics & Materials', lesson_index: 5, exercise_count: 10 },
  { id: 211, unit_id: 13, title: 'Tailoring & Fit', lesson_index: 6, exercise_count: 10 },
  { id: 212, unit_id: 13, title: 'Clothing Review II', lesson_index: 7, exercise_count: 10 },
  { id: 213, unit_id: 14, title: 'Giving Directions', lesson_index: 4, exercise_count: 10 },
  { id: 214, unit_id: 14, title: 'Asking for Directions', lesson_index: 5, exercise_count: 10 },
  { id: 215, unit_id: 14, title: 'Maps & Navigation', lesson_index: 6, exercise_count: 10 },
  { id: 216, unit_id: 14, title: 'Directions Review II', lesson_index: 7, exercise_count: 10 },
  { id: 217, unit_id: 15, title: 'Air Travel', lesson_index: 4, exercise_count: 10 },
  { id: 218, unit_id: 15, title: 'Sea Travel', lesson_index: 5, exercise_count: 10 },
  { id: 219, unit_id: 15, title: 'Road Safety', lesson_index: 6, exercise_count: 10 },
  { id: 220, unit_id: 15, title: 'Transport Review II', lesson_index: 7, exercise_count: 10 },
  { id: 221, unit_id: 16, title: 'Bargaining Phrases', lesson_index: 4, exercise_count: 10 },
  { id: 222, unit_id: 16, title: 'Payment Methods', lesson_index: 5, exercise_count: 10 },
  { id: 223, unit_id: 16, title: 'Investments', lesson_index: 6, exercise_count: 10 },
  { id: 224, unit_id: 16, title: 'Shopping Review II', lesson_index: 7, exercise_count: 10 },
  { id: 225, unit_id: 17, title: 'Common Illnesses', lesson_index: 4, exercise_count: 10 },
  { id: 226, unit_id: 17, title: 'At the Pharmacy', lesson_index: 5, exercise_count: 10 },
  { id: 227, unit_id: 17, title: 'Prevention & Wellness', lesson_index: 6, exercise_count: 10 },
  { id: 228, unit_id: 17, title: 'Health Review II', lesson_index: 7, exercise_count: 10 },
  { id: 229, unit_id: 18, title: 'Higher Education', lesson_index: 4, exercise_count: 10 },
  { id: 230, unit_id: 18, title: 'Job Applications', lesson_index: 5, exercise_count: 10 },
  { id: 231, unit_id: 18, title: 'Workplace Communication', lesson_index: 6, exercise_count: 10 },
  { id: 232, unit_id: 18, title: 'School & Work Review II', lesson_index: 7, exercise_count: 10 },
  { id: 233, unit_id: 19, title: 'Climate & Seasons', lesson_index: 4, exercise_count: 10 },
  { id: 234, unit_id: 19, title: 'Natural Disasters', lesson_index: 5, exercise_count: 10 },
  { id: 235, unit_id: 19, title: 'Environment', lesson_index: 6, exercise_count: 10 },
  { id: 236, unit_id: 19, title: 'Nature Review II', lesson_index: 7, exercise_count: 10 },
  { id: 237, unit_id: 20, title: 'Social Phrases', lesson_index: 4, exercise_count: 10 },
  { id: 238, unit_id: 20, title: 'Expressing Opinions', lesson_index: 5, exercise_count: 10 },
  { id: 239, unit_id: 20, title: 'Proverbs & Sayings', lesson_index: 6, exercise_count: 10 },
  { id: 240, unit_id: 20, title: 'Phrases Review II', lesson_index: 7, exercise_count: 10 },
  { id: 241, unit_id: 21, title: 'Pronoun Practice', lesson_index: 4, exercise_count: 10 },
  { id: 242, unit_id: 21, title: 'Copula Sentences', lesson_index: 5, exercise_count: 10 },
  { id: 243, unit_id: 21, title: 'Question Formation', lesson_index: 6, exercise_count: 10 },
  { id: 244, unit_id: 21, title: 'Pronouns Review II', lesson_index: 7, exercise_count: 10 },
  { id: 245, unit_id: 22, title: 'More Present Tense Verbs', lesson_index: 4, exercise_count: 10 },
  { id: 246, unit_id: 22, title: 'Present Progressive', lesson_index: 5, exercise_count: 10 },
  { id: 247, unit_id: 22, title: 'Habitual Present', lesson_index: 6, exercise_count: 10 },
  { id: 248, unit_id: 22, title: 'Present Tense Review II', lesson_index: 7, exercise_count: 10 },
  { id: 249, unit_id: 23, title: 'Negating More Verbs', lesson_index: 4, exercise_count: 10 },
  { id: 250, unit_id: 23, title: 'Negative Questions', lesson_index: 5, exercise_count: 10 },
  { id: 251, unit_id: 23, title: 'Double Negatives', lesson_index: 6, exercise_count: 10 },
  { id: 252, unit_id: 23, title: 'Negation Review II', lesson_index: 7, exercise_count: 10 },
  { id: 253, unit_id: 24, title: 'More Past Verbs', lesson_index: 4, exercise_count: 10 },
  { id: 254, unit_id: 24, title: 'Past Experiences', lesson_index: 5, exercise_count: 10 },
  { id: 255, unit_id: 24, title: 'Past Narration', lesson_index: 6, exercise_count: 10 },
  { id: 256, unit_id: 24, title: 'Past Tense Review II', lesson_index: 7, exercise_count: 10 },
  { id: 257, unit_id: 25, title: 'Future Plans', lesson_index: 4, exercise_count: 10 },
  { id: 258, unit_id: 25, title: 'Future Intentions', lesson_index: 5, exercise_count: 10 },
  { id: 259, unit_id: 25, title: 'Near vs Far Future', lesson_index: 6, exercise_count: 10 },
  { id: 260, unit_id: 25, title: 'Future Review II', lesson_index: 7, exercise_count: 10 },
  { id: 261, unit_id: 26, title: 'Calendar Events', lesson_index: 4, exercise_count: 10 },
  { id: 262, unit_id: 26, title: 'Appointments', lesson_index: 5, exercise_count: 10 },
  { id: 263, unit_id: 26, title: 'Holidays & Festivals', lesson_index: 6, exercise_count: 10 },
  { id: 264, unit_id: 26, title: 'Time Review II', lesson_index: 7, exercise_count: 10 },
  { id: 265, unit_id: 27, title: 'Birds & Insects', lesson_index: 4, exercise_count: 10 },
  { id: 266, unit_id: 27, title: 'Farm Animals', lesson_index: 5, exercise_count: 10 },
  { id: 267, unit_id: 27, title: 'Animal Sounds', lesson_index: 6, exercise_count: 10 },
  { id: 268, unit_id: 27, title: 'Animals Review II', lesson_index: 7, exercise_count: 10 },
  { id: 269, unit_id: 28, title: 'Creative Jobs', lesson_index: 4, exercise_count: 10 },
  { id: 270, unit_id: 28, title: 'Service Jobs', lesson_index: 5, exercise_count: 10 },
  { id: 271, unit_id: 28, title: 'Job Responsibilities', lesson_index: 6, exercise_count: 10 },
  { id: 272, unit_id: 28, title: 'Jobs Review II', lesson_index: 7, exercise_count: 10 },
  { id: 273, unit_id: 29, title: 'Hundreds Practice', lesson_index: 4, exercise_count: 10 },
  { id: 274, unit_id: 29, title: 'Thousands Practice', lesson_index: 5, exercise_count: 10 },
  { id: 275, unit_id: 29, title: 'Fractions & Decimals', lesson_index: 6, exercise_count: 10 },
  { id: 276, unit_id: 29, title: 'Numbers Review II', lesson_index: 7, exercise_count: 10 },
  { id: 277, unit_id: 30, title: 'More Object Infixes', lesson_index: 4, exercise_count: 10 },
  { id: 278, unit_id: 30, title: 'Infix Practice', lesson_index: 5, exercise_count: 10 },
  { id: 279, unit_id: 30, title: 'Complex Infixes', lesson_index: 6, exercise_count: 10 },
  { id: 280, unit_id: 30, title: 'Infix Review II', lesson_index: 7, exercise_count: 10 },
  { id: 281, unit_id: 31, title: 'Extreme Sports', lesson_index: 4, exercise_count: 10 },
  { id: 282, unit_id: 31, title: 'Sports Culture', lesson_index: 5, exercise_count: 10 },
  { id: 283, unit_id: 31, title: 'Fitness & Training', lesson_index: 6, exercise_count: 10 },
  { id: 284, unit_id: 31, title: 'Sports Review II', lesson_index: 7, exercise_count: 10 },
  { id: 285, unit_id: 32, title: 'Digital Life', lesson_index: 4, exercise_count: 10 },
  { id: 286, unit_id: 32, title: 'Online Safety', lesson_index: 5, exercise_count: 10 },
  { id: 287, unit_id: 32, title: 'Tech Support', lesson_index: 6, exercise_count: 10 },
  { id: 288, unit_id: 32, title: 'Technology Review II', lesson_index: 7, exercise_count: 10 },
  { id: 289, unit_id: 33, title: 'Packing & Preparation', lesson_index: 4, exercise_count: 10 },
  { id: 290, unit_id: 33, title: 'At the Destination', lesson_index: 5, exercise_count: 10 },
  { id: 291, unit_id: 33, title: 'Travel Problems', lesson_index: 6, exercise_count: 10 },
  { id: 292, unit_id: 33, title: 'Travel Review II', lesson_index: 7, exercise_count: 10 },
  { id: 293, unit_id: 34, title: 'More Ordinals', lesson_index: 4, exercise_count: 10 },
  { id: 294, unit_id: 34, title: 'Comparative Sentences', lesson_index: 5, exercise_count: 10 },
  { id: 295, unit_id: 34, title: 'Equality Expressions', lesson_index: 6, exercise_count: 10 },
  { id: 296, unit_id: 34, title: 'Comparison Review II', lesson_index: 7, exercise_count: 10 },
  { id: 297, unit_id: 35, title: 'Cooking Measurements', lesson_index: 4, exercise_count: 10 },
  { id: 298, unit_id: 35, title: 'Construction Measurements', lesson_index: 5, exercise_count: 10 },
  { id: 299, unit_id: 35, title: 'Scientific Units', lesson_index: 6, exercise_count: 10 },
  { id: 300, unit_id: 35, title: 'Measurements Review II', lesson_index: 7, exercise_count: 10 },
  { id: 301, unit_id: 36, title: 'Weekend Routine', lesson_index: 4, exercise_count: 10 },
  { id: 302, unit_id: 36, title: 'Holiday Routine', lesson_index: 5, exercise_count: 10 },
  { id: 303, unit_id: 36, title: 'Time Management', lesson_index: 6, exercise_count: 10 },
  { id: 304, unit_id: 36, title: 'Daily Life Review II', lesson_index: 7, exercise_count: 10 },
  { id: 305, unit_id: 37, title: 'More EA Countries', lesson_index: 4, exercise_count: 10 },
  { id: 306, unit_id: 37, title: 'Cities of EA', lesson_index: 5, exercise_count: 10 },
  { id: 307, unit_id: 37, title: 'Cultural Events', lesson_index: 6, exercise_count: 10 },
  { id: 308, unit_id: 37, title: 'Geography Review II', lesson_index: 7, exercise_count: 10 },
  { id: 309, unit_id: 38, title: 'Formal Letters', lesson_index: 4, exercise_count: 10 },
  { id: 310, unit_id: 38, title: 'Ceremonial Speech', lesson_index: 5, exercise_count: 10 },
  { id: 311, unit_id: 38, title: 'Workplace Politeness', lesson_index: 6, exercise_count: 10 },
  { id: 312, unit_id: 38, title: 'Formal Review II', lesson_index: 7, exercise_count: 10 },
  { id: 313, unit_id: 39, title: 'TV & Streaming', lesson_index: 4, exercise_count: 10 },
  { id: 314, unit_id: 39, title: 'Radio & Podcasts', lesson_index: 5, exercise_count: 10 },
  { id: 315, unit_id: 39, title: 'Gaming & Digital', lesson_index: 6, exercise_count: 10 },
  { id: 316, unit_id: 39, title: 'Media Review II', lesson_index: 7, exercise_count: 10 },
  { id: 317, unit_id: 40, title: 'International Relations', lesson_index: 4, exercise_count: 10 },
  { id: 318, unit_id: 40, title: 'Civil Rights', lesson_index: 5, exercise_count: 10 },
  { id: 319, unit_id: 40, title: 'Local Government', lesson_index: 6, exercise_count: 10 },
  { id: 320, unit_id: 40, title: 'Politics Review II', lesson_index: 7, exercise_count: 10 },
];
